#include "Includes/Common.hlsl"

cbuffer GFD_PSCONST_SYSTEM : register(b0)
{
	float2 resolution : packoffset(c0);
	float2 resolutionRev : packoffset(c0.z);
	float4x4 mtxView : packoffset(c1);
	float4x4 mtxInvView : packoffset(c5);
	float4x4 mtxProj : packoffset(c9);
	float4x4 mtxInvProj : packoffset(c13);
	float4 invProjParams : packoffset(c17);
}

cbuffer GFD_PSCONST_SSAO : register(b12)
{
	float4 uvToViewParams : packoffset(c0);
	float4 screenParams : packoffset(c1);
	float4 radiusParams : packoffset(c2);
	float4 focalParams : packoffset(c3);
	float4 biasParams : packoffset(c4);
	float4 compositeColor : packoffset(c5);
}

SamplerState pointSampler_s : register(s0);
SamplerState linearSampler_s : register(s1);
Texture2D<float4> depthTexture : register(t0);
Texture2D<float4> gbuffer1Texture : register(t1);
Texture2D<float4> randomTexture : register(t2);

uint RandomFromIndex(int i)
{
	// Convert index to float, apply some constants and sine hash
	return uint(frac(sin(float(i) * 12.9898 + 78.233) * 43758.5453) * 32.0f);
}

float RandomFromIndex2(int i)
{
	// Convert index to float, apply some constants and sine hash
	return uint(frac(sin(float(i) * 14.9898 + 72.233) * 48758.5453) * 32.0f);
}

void main(
	float4 v0 : SV_POSITION0,
	float2 v1 : TEXCOORD0,
	out float2 o0 : SV_Target0)
{
	float4 r0,r1,r2,r3,r4,r5,r6,r7,r8,r9;
	uint4 bitmask, uiDest;
	float4 fDest;

	r0.x = depthTexture.Sample(pointSampler_s, v1.xy).x;
	r0.x = invProjParams.z + r0.x;
	r0.x = invProjParams.w / r0.x;
	r0.w = -r0.x;
	r1.x = gbuffer1Texture.Sample(pointSampler_s, v1.xy).w;
	r1.x = 255 * r1.x;
	r1.x = (uint)r1.x;
	r1.x = (int)r1.x & 2;
	if (r1.x != 0) {
		r0.x = 1;
		o0.xy = r0.xw;
		return;
	}
	r1.x = focalParams.x * radiusParams.x;
	r1.x = 0.5 * r1.x;
	r1.x = r1.x / r0.w;
	r1.x = screenParams.x * r1.x;
	r1.y = r1.x < 1;
	if (r1.y != 0) {
		r0.y = 1;
		o0.xy = r0.yw;
		return;
	}
	r1.yz = uvToViewParams.xy * v1.xy + uvToViewParams.zw;
	r0.yz = r1.yz * r0.ww;
	{
		float2 noiseSampleCoord = float2(0.03125,0.03125) * v0.xy;
		r1.yzw = randomTexture.Sample(linearSampler_s, noiseSampleCoord).xyz;
		if(LumaSettings.SRType == 1) //only DLSS for now, current spatial denoise makes noise look like features to FSR
		{
			uint2 randomOffset = uint2(RandomFromIndex(LumaSettings.GameSettings.FrameIndex), RandomFromIndex2(LumaSettings.GameSettings.FrameIndex));
			noiseSampleCoord = float2(0.03125,0.03125) * (v0.xy + randomOffset);
			r1.zw = randomTexture.Sample(linearSampler_s, noiseSampleCoord).yz;
		}
		//apply bias from original noise
		r1.y = pow(r1.y, 0.2f);
		r1.y *= 0.3f;
		r1.y += 0.7f;
		r1.z *= 0.7f;
	}
	r2.x = screenParams.z;
	r2.yw = float2(0,0);
	r2.xy = v1.xy + r2.xy;
	r3.x = depthTexture.Sample(pointSampler_s, r2.xy).x;
	r3.x = invProjParams.z + r3.x;
	r3.x = invProjParams.w / r3.x;
	r3.z = -r3.x;
	r2.xy = uvToViewParams.xy * r2.xy + uvToViewParams.zw;
	r3.xy = r2.xy * r3.zz;
	r2.z = -screenParams.z;
	r2.xy = v1.xy + r2.zw;
	r2.z = depthTexture.Sample(pointSampler_s, r2.xy).x;
	r2.z = invProjParams.z + r2.z;
	r2.z = invProjParams.w / r2.z;
	r4.z = -r2.z;
	r2.xy = uvToViewParams.xy * r2.xy + uvToViewParams.zw;
	r4.xy = r2.xy * r4.zz;
	r2.xz = float2(0,0);
	r2.y = screenParams.w;
	r2.xy = v1.xy + r2.xy;
	r3.w = depthTexture.Sample(pointSampler_s, r2.xy).x;
	r3.w = invProjParams.z + r3.w;
	r3.w = invProjParams.w / r3.w;
	r5.z = -r3.w;
	r2.xy = uvToViewParams.xy * r2.xy + uvToViewParams.zw;
	r5.xy = r2.xy * r5.zz;
	r2.w = -screenParams.w;
	r2.xy = v1.xy + r2.zw;
	r2.z = depthTexture.Sample(pointSampler_s, r2.xy).x;
	r2.z = invProjParams.z + r2.z;
	r2.z = invProjParams.w / r2.z;
	r6.z = -r2.z;
	r2.xy = uvToViewParams.xy * r2.xy + uvToViewParams.zw;
	r6.xy = r2.xy * r6.zz;
	r2.xyz = r3.xyz + -r0.yzw;
	r3.xyz = -r4.xyz + r0.yzw;
	r2.w = dot(r2.xyz, r2.xyz);
	r3.w = dot(r3.xyz, r3.xyz);
	r2.w = r2.w < r3.w;
	r2.xyz = r2.www ? r2.xyz : r3.xyz;
	r3.xyz = r5.xyz + -r0.yzw;
	r4.xyz = -r6.xyz + r0.yzw;
	r2.w = dot(r3.xyz, r3.xyz);
	r3.w = dot(r4.xyz, r4.xyz);
	r2.w = r2.w < r3.w;
	r3.xyz = r2.www ? r3.xyz : r4.xyz;
	r2.w = screenParams.y * screenParams.z;
	r3.xyz = r3.xyz * r2.www;
	r4.x = min(4, r1.x);
	r2.w = 1 + r4.x;
	r4.y = r1.x / r2.w;
	r1.x = radiusParams.w / r4.y;
	r2.w = r1.x < r4.x;
	r1.x = r1.x + r1.w;
	r1.x = floor(r1.x);
	r5.x = max(1, r1.x);
	r5.y = radiusParams.w / r5.x;
	r4.xy = r2.ww ? r5.xy : r4.xy;
	r4.yz = screenParams.zw * r4.yy;
	r5.xy = r4.yz * r1.yz;
	r5.zw = screenParams.zw * r1.yz;
	r6.xy = r5.xy * r1.ww;
	r6.xy = screenParams.xy * r6.xy;
	r6.xy = round(r6.xy);
	r6.xy = r6.xy * screenParams.zw + v1.xy;
	r5.xy = screenParams.xy * r5.xy;
	r5.xy = round(r5.xy);
	r6.zw = screenParams.zw * r5.xy;
	r7.xyz = r6.www * r3.xyz;
	r7.xyz = r6.zzz * r2.xyz + r7.xyz;
	r1.x = dot(r7.xy, r7.xy);
	r1.x = rsqrt(r1.x);
	r7.x = -r7.z * r1.x + biasParams.y;
	r5.zw = r1.ww * r6.zw + r5.zw;
	r5.zw = screenParams.xy * r5.zw;
	r5.zw = round(r5.zw);
	r6.zw = screenParams.zw * r5.zw;
	r8.xyz = r6.www * r3.xyz;
	r8.xyz = r6.zzz * r2.xyz + r8.xyz;
	r1.x = dot(r8.xy, r8.xy);
	r1.x = rsqrt(r1.x);
	r1.x = -r8.z * r1.x + biasParams.y;
	r2.w = r1.x * r1.x + 1;
	r2.w = rsqrt(r2.w);
	r2.w = r2.w * r1.x;
	r5.zw = r5.zw * screenParams.zw + v1.xy;
	r3.w = depthTexture.Sample(pointSampler_s, r5.zw).x;
	r3.w = invProjParams.z + r3.w;
	r3.w = invProjParams.w / r3.w;
	r8.z = -r3.w;
	r5.zw = uvToViewParams.xy * r5.zw + uvToViewParams.zw;
	r8.xy = r5.zw * r8.zz;
	r8.xyz = r8.xyz + -r0.yzw;
	r3.w = dot(r8.xy, r8.xy);
	r3.w = rsqrt(r3.w);
	r3.w = -r8.z * r3.w;
	r4.w = r3.w * r3.w + 1;
	r4.w = rsqrt(r4.w);
	r5.z = dot(r8.xyz, r8.xyz);
	r5.w = r5.z < radiusParams.y;
	r1.x = r1.x < r3.w;
	r1.x = r1.x ? r5.w : 0;
	r5.z = r5.z * radiusParams.z + 1;
	r2.w = saturate(r3.w * r4.w + -r2.w);
	r8.y = r5.z * r2.w;
	r8.x = max(r7.x, r3.w);
	r7.yw = float2(0,0);
	r5.zw = r1.xx ? r8.xy : r7.xy;
	r1.x = -1 + r4.x;
	r2.w = r5.z * r5.z + 1;
	r2.w = rsqrt(r2.w);
	r2.w = r5.z * r2.w;
	r3.w = 1 < r1.x;
	if (r3.w != 0) {
		r6.xy = r5.xy * screenParams.zw + r6.xy;
		r4.x = depthTexture.Sample(pointSampler_s, r6.xy).x;
		r4.x = invProjParams.z + r4.x;
		r4.x = invProjParams.w / r4.x;
		r8.z = -r4.x;
		r4.xw = uvToViewParams.xy * r6.xy + uvToViewParams.zw;
		r8.xy = r4.xw * r8.zz;
		r8.xyz = r8.xyz + -r0.yzw;
		r4.x = dot(r8.xy, r8.xy);
		r4.x = rsqrt(r4.x);
		r4.x = -r8.z * r4.x;
		r4.w = dot(r8.xyz, r8.xyz);
		r6.z = r4.w < radiusParams.y;
		r6.w = r5.z < r4.x;
		r6.z = r6.w ? r6.z : 0;
		if (r6.z != 0) {
			r6.z = r4.x * r4.x + 1;
			r6.z = rsqrt(r6.z);
			r6.w = r6.z * r4.x;
			r4.w = r4.w * radiusParams.z + 1;
			r6.z = saturate(r4.x * r6.z + -r2.w);
			r4.w = r4.w * r6.z + r5.w;
			r5.z = r4.x;
			r2.w = r6.w;
		} else {
			r4.w = r5.w;
		}
		r5.w = 2;
	} else {
		r4.w = r5.w;
		r5.w = 1;
	}
	r4.x = r5.w < r1.x;
	if (r4.x != 0) {
		r6.xy = r5.xy * screenParams.zw + r6.xy;
		r6.z = depthTexture.Sample(pointSampler_s, r6.xy).x;
		r6.z = invProjParams.z + r6.z;
		r6.z = invProjParams.w / r6.z;
		r8.z = -r6.z;
		r6.zw = uvToViewParams.xy * r6.xy + uvToViewParams.zw;
		r8.xy = r6.zw * r8.zz;
		r8.xyz = r8.xyz + -r0.yzw;
		r6.z = dot(r8.xy, r8.xy);
		r6.z = rsqrt(r6.z);
		r6.z = -r8.z * r6.z;
		r6.w = dot(r8.xyz, r8.xyz);
		r7.x = r6.w < radiusParams.y;
		r7.y = r5.z < r6.z;
		r7.x = r7.y ? r7.x : 0;
		if (r7.x != 0) {
			r7.x = r6.z * r6.z + 1;
			r7.x = rsqrt(r7.x);
			r7.y = r7.x * r6.z;
			r6.w = r6.w * radiusParams.z + 1;
			r7.x = saturate(r6.z * r7.x + -r2.w);
			r4.w = r6.w * r7.x + r4.w;
			r5.z = r6.z;
			r2.w = r7.y;
		}
		r5.w = 3;
	}
	r6.z = r5.w < r1.x;
	r4.x = r4.x ? r6.z : 0;
	if (r4.x != 0) {
		r6.xy = r5.xy * screenParams.zw + r6.xy;
		r6.z = depthTexture.Sample(pointSampler_s, r6.xy).x;
		r6.z = invProjParams.z + r6.z;
		r6.z = invProjParams.w / r6.z;
		r8.z = -r6.z;
		r6.zw = uvToViewParams.xy * r6.xy + uvToViewParams.zw;
		r8.xy = r6.zw * r8.zz;
		r8.xyz = r8.xyz + -r0.yzw;
		r6.z = dot(r8.xy, r8.xy);
		r6.z = rsqrt(r6.z);
		r6.z = -r8.z * r6.z;
		r6.w = dot(r8.xyz, r8.xyz);
		r7.x = r6.w < radiusParams.y;
		r7.y = r5.z < r6.z;
		r7.x = r7.y ? r7.x : 0;
		if (r7.x != 0) {
			r7.x = r6.z * r6.z + 1;
			r7.x = rsqrt(r7.x);
			r7.y = r7.x * r6.z;
			r6.w = r6.w * radiusParams.z + 1;
			r7.x = saturate(r6.z * r7.x + -r2.w);
			r4.w = r6.w * r7.x + r4.w;
			r5.z = r6.z;
			r2.w = r7.y;
		}
		r5.w = 4;
	}
	r5.w = r5.w < r1.x;
	r4.x = r4.x ? r5.w : 0;
	if (r4.x != 0) {
		r5.xy = r5.xy * screenParams.zw + r6.xy;
		r4.x = depthTexture.Sample(pointSampler_s, r5.xy).x;
		r4.x = invProjParams.z + r4.x;
		r4.x = invProjParams.w / r4.x;
		r6.z = -r4.x;
		r5.xy = uvToViewParams.xy * r5.xy + uvToViewParams.zw;
		r6.xy = r5.xy * r6.zz;
		r5.xyw = r6.xyz + -r0.yzw;
		r4.x = dot(r5.xy, r5.xy);
		r4.x = rsqrt(r4.x);
		r4.x = -r5.w * r4.x;
		r5.x = dot(r5.xyw, r5.xyw);
		r5.y = r5.x < radiusParams.y;
		r5.z = r5.z < r4.x;
		r5.y = r5.z ? r5.y : 0;
		if (r5.y != 0) {
			r5.y = r4.x * r4.x + 1;
			r5.y = rsqrt(r5.y);
			r5.x = r5.x * radiusParams.z + 1;
			r2.w = saturate(r4.x * r5.y + -r2.w);
			r4.w = r5.x * r2.w + r4.w;
		}
	}
	r5.xy = float2(0.707106769,0.707106769) * r1.yz;
	r6.x = r1.y * 0.707106769 + -r5.y;
	r6.y = r5.y + r5.x;
	r5.zw = r6.xy * r4.yz;
	r6.zw = r5.zw * r1.ww;
	r6.xyzw = screenParams.zwxy * r6.xyzw;
	r6.zw = round(r6.zw);
	r6.zw = r6.zw * screenParams.zw + v1.xy;
	r5.zw = screenParams.xy * r5.zw;
	r5.zw = round(r5.zw);
	r7.xy = screenParams.zw * r5.zw;
	r8.xyz = r7.yyy * r3.xyz;
	r8.xyz = r7.xxx * r2.xyz + r8.xyz;
	r2.w = dot(r8.xy, r8.xy);
	r2.w = rsqrt(r2.w);
	r7.z = -r8.z * r2.w + biasParams.y;
	r6.xy = r1.ww * r7.xy + r6.xy;
	r6.xy = screenParams.xy * r6.xy;
	r6.xy = round(r6.xy);
	r7.xy = screenParams.zw * r6.xy;
	r8.xyz = r7.yyy * r3.xyz;
	r8.xyz = r7.xxx * r2.xyz + r8.xyz;
	r2.w = dot(r8.xy, r8.xy);
	r2.w = rsqrt(r2.w);
	r2.w = -r8.z * r2.w + biasParams.y;
	r4.x = r2.w * r2.w + 1;
	r4.x = rsqrt(r4.x);
	r4.x = r4.x * r2.w;
	r6.xy = r6.xy * screenParams.zw + v1.xy;
	r7.x = depthTexture.Sample(pointSampler_s, r6.xy).x;
	r7.x = invProjParams.z + r7.x;
	r7.x = invProjParams.w / r7.x;
	r8.z = -r7.x;
	r6.xy = uvToViewParams.xy * r6.xy + uvToViewParams.zw;
	r8.xy = r6.xy * r8.zz;
	r8.xyz = r8.xyz + -r0.yzw;
	r6.x = dot(r8.xy, r8.xy);
	r6.x = rsqrt(r6.x);
	r6.x = -r8.z * r6.x;
	r6.y = r6.x * r6.x + 1;
	r6.y = rsqrt(r6.y);
	r7.x = dot(r8.xyz, r8.xyz);
	r7.y = r7.x < radiusParams.y;
	r2.w = r2.w < r6.x;
	r2.w = r2.w ? r7.y : 0;
	r7.x = r7.x * radiusParams.z + 1;
	r4.x = saturate(r6.x * r6.y + -r4.x);
	r7.y = r7.x * r4.x;
	r7.x = max(r7.z, r6.x);
	r6.xy = r2.ww ? r7.xy : r7.zw;
	r2.w = r6.x * r6.x + 1;
	r2.w = rsqrt(r2.w);
	r2.w = r6.x * r2.w;
	if (r3.w != 0) {
		r6.zw = r5.zw * screenParams.zw + r6.zw;
		r4.x = depthTexture.Sample(pointSampler_s, r6.zw).x;
		r4.x = invProjParams.z + r4.x;
		r4.x = invProjParams.w / r4.x;
		r7.z = -r4.x;
		r8.xy = uvToViewParams.xy * r6.zw + uvToViewParams.zw;
		r7.xy = r8.xy * r7.zz;
		r7.xyz = r7.xyz + -r0.yzw;
		r4.x = dot(r7.xy, r7.xy);
		r4.x = rsqrt(r4.x);
		r4.x = -r7.z * r4.x;
		r7.x = dot(r7.xyz, r7.xyz);
		r7.y = r7.x < radiusParams.y;
		r7.z = r6.x < r4.x;
		r7.y = r7.z ? r7.y : 0;
		if (r7.y != 0) {
			r7.y = r4.x * r4.x + 1;
			r7.y = rsqrt(r7.y);
			r7.z = r7.y * r4.x;
			r7.x = r7.x * radiusParams.z + 1;
			r7.y = saturate(r4.x * r7.y + -r2.w);
			r7.x = r7.x * r7.y + r6.y;
			r6.x = r4.x;
			r2.w = r7.z;
		} else {
			r7.x = r6.y;
		}
		r6.y = 2;
	} else {
		r7.x = r6.y;
		r6.y = 1;
	}
	r4.x = r6.y < r1.x;
	if (r4.x != 0) {
		r6.zw = r5.zw * screenParams.zw + r6.zw;
		r7.y = depthTexture.Sample(pointSampler_s, r6.zw).x;
		r7.y = invProjParams.z + r7.y;
		r7.y = invProjParams.w / r7.y;
		r8.z = -r7.y;
		r7.yz = uvToViewParams.xy * r6.zw + uvToViewParams.zw;
		r8.xy = r7.yz * r8.zz;
		r7.yzw = r8.xyz + -r0.yzw;
		r8.x = dot(r7.yz, r7.yz);
		r8.x = rsqrt(r8.x);
		r8.x = r8.x * -r7.w;
		r7.y = dot(r7.yzw, r7.yzw);
		r7.z = r7.y < radiusParams.y;
		r7.w = r6.x < r8.x;
		r7.z = r7.w ? r7.z : 0;
		if (r7.z != 0) {
			r7.z = r8.x * r8.x + 1;
			r7.z = rsqrt(r7.z);
			r7.w = r8.x * r7.z;
			r7.y = r7.y * radiusParams.z + 1;
			r7.z = saturate(r8.x * r7.z + -r2.w);
			r7.x = r7.y * r7.z + r7.x;
			r6.x = r8.x;
			r2.w = r7.w;
		}
		r6.y = 3;
	}
	r7.y = r6.y < r1.x;
	r4.x = r4.x ? r7.y : 0;
	if (r4.x != 0) {
		r6.zw = r5.zw * screenParams.zw + r6.zw;
		r7.y = depthTexture.Sample(pointSampler_s, r6.zw).x;
		r7.y = invProjParams.z + r7.y;
		r7.y = invProjParams.w / r7.y;
		r8.z = -r7.y;
		r7.yz = uvToViewParams.xy * r6.zw + uvToViewParams.zw;
		r8.xy = r7.yz * r8.zz;
		r7.yzw = r8.xyz + -r0.yzw;
		r8.x = dot(r7.yz, r7.yz);
		r8.x = rsqrt(r8.x);
		r8.x = r8.x * -r7.w;
		r7.y = dot(r7.yzw, r7.yzw);
		r7.z = r7.y < radiusParams.y;
		r7.w = r6.x < r8.x;
		r7.z = r7.w ? r7.z : 0;
		if (r7.z != 0) {
			r7.z = r8.x * r8.x + 1;
			r7.z = rsqrt(r7.z);
			r7.w = r8.x * r7.z;
			r7.y = r7.y * radiusParams.z + 1;
			r7.z = saturate(r8.x * r7.z + -r2.w);
			r7.x = r7.y * r7.z + r7.x;
			r6.x = r8.x;
			r2.w = r7.w;
		}
		r6.y = 4;
	}
	r6.y = r6.y < r1.x;
	r4.x = r4.x ? r6.y : 0;
	if (r4.x != 0) {
		r5.zw = r5.zw * screenParams.zw + r6.zw;
		r4.x = depthTexture.Sample(pointSampler_s, r5.zw).x;
		r4.x = invProjParams.z + r4.x;
		r4.x = invProjParams.w / r4.x;
		r8.z = -r4.x;
		r5.zw = uvToViewParams.xy * r5.zw + uvToViewParams.zw;
		r8.xy = r5.zw * r8.zz;
		r6.yzw = r8.xyz + -r0.yzw;
		r4.x = dot(r6.yz, r6.yz);
		r4.x = rsqrt(r4.x);
		r4.x = -r6.w * r4.x;
		r5.z = dot(r6.yzw, r6.yzw);
		r5.w = r5.z < radiusParams.y;
		r6.x = r6.x < r4.x;
		r5.w = r5.w ? r6.x : 0;
		if (r5.w != 0) {
			r5.w = r4.x * r4.x + 1;
			r5.w = rsqrt(r5.w);
			r5.z = r5.z * radiusParams.z + 1;
			r2.w = saturate(r4.x * r5.w + -r2.w);
			r7.x = r5.z * r2.w + r7.x;
		}
	}
	r2.w = r7.x + r4.w;
	r6.x = r1.y * -4.37113883e-08 + -r1.z;
	r6.y = r1.z * -4.37113883e-08 + r1.y;
	r4.xw = r6.xy * r4.yz;
	r5.zw = screenParams.zw * r6.xy;
	r6.xy = r4.xw * r1.ww;
	r6.xy = screenParams.xy * r6.xy;
	r6.xy = round(r6.xy);
	r6.xy = r6.xy * screenParams.zw + v1.xy;
	r4.xw = screenParams.xy * r4.xw;
	r4.xw = round(r4.xw);
	r6.zw = screenParams.zw * r4.xw;
	r7.xyz = r6.www * r3.xyz;
	r7.xyz = r6.zzz * r2.xyz + r7.xyz;
	r7.x = dot(r7.xy, r7.xy);
	r7.x = rsqrt(r7.x);
	r7.x = -r7.z * r7.x + biasParams.y;
	r5.zw = r1.ww * r6.zw + r5.zw;
	r5.zw = screenParams.xy * r5.zw;
	r5.zw = round(r5.zw);
	r6.zw = screenParams.zw * r5.zw;
	r8.xyz = r6.www * r3.xyz;
	r8.xyz = r6.zzz * r2.xyz + r8.xyz;
	r6.z = dot(r8.xy, r8.xy);
	r6.z = rsqrt(r6.z);
	r6.z = -r8.z * r6.z + biasParams.y;
	r6.w = r6.z * r6.z + 1;
	r6.w = rsqrt(r6.w);
	r6.w = r6.z * r6.w;
	r5.zw = r5.zw * screenParams.zw + v1.xy;
	r8.x = depthTexture.Sample(pointSampler_s, r5.zw).x;
	r8.x = invProjParams.z + r8.x;
	r8.x = invProjParams.w / r8.x;
	r8.z = -r8.x;
	r5.zw = uvToViewParams.xy * r5.zw + uvToViewParams.zw;
	r8.xy = r5.zw * r8.zz;
	r8.xyz = r8.xyz + -r0.yzw;
	r5.z = dot(r8.xy, r8.xy);
	r5.z = rsqrt(r5.z);
	r5.z = -r8.z * r5.z;
	r5.w = r5.z * r5.z + 1;
	r5.w = rsqrt(r5.w);
	r8.x = dot(r8.xyz, r8.xyz);
	r8.y = r8.x < radiusParams.y;
	r6.z = r6.z < r5.z;
	r6.z = r6.z ? r8.y : 0;
	r8.x = r8.x * radiusParams.z + 1;
	r5.w = saturate(r5.z * r5.w + -r6.w);
	r8.y = r8.x * r5.w;
	r8.x = max(r7.x, r5.z);
	r7.yw = float2(0,0);
	r5.zw = r6.zz ? r8.xy : r7.xy;
	r6.z = r5.z * r5.z + 1;
	r6.z = rsqrt(r6.z);
	r6.z = r6.z * r5.z;
	if (r3.w != 0) {
		r6.xy = r4.xw * screenParams.zw + r6.xy;
		r6.w = depthTexture.Sample(pointSampler_s, r6.xy).x;
		r6.w = invProjParams.z + r6.w;
		r6.w = invProjParams.w / r6.w;
		r8.z = -r6.w;
		r7.xy = uvToViewParams.xy * r6.xy + uvToViewParams.zw;
		r8.xy = r7.xy * r8.zz;
		r8.xyz = r8.xyz + -r0.yzw;
		r6.w = dot(r8.xy, r8.xy);
		r6.w = rsqrt(r6.w);
		r6.w = -r8.z * r6.w;
		r7.x = dot(r8.xyz, r8.xyz);
		r7.y = r7.x < radiusParams.y;
		r8.x = r5.z < r6.w;
		r7.y = r7.y ? r8.x : 0;
		if (r7.y != 0) {
			r7.y = r6.w * r6.w + 1;
			r7.y = rsqrt(r7.y);
			r8.x = r7.y * r6.w;
			r7.x = r7.x * radiusParams.z + 1;
			r7.y = saturate(r6.w * r7.y + -r6.z);
			r7.x = r7.x * r7.y + r5.w;
			r5.z = r6.w;
			r6.z = r8.x;
		} else {
			r7.x = r5.w;
		}
		r5.w = 2;
	} else {
		r7.x = r5.w;
		r5.w = 1;
	}
	r6.w = r5.w < r1.x;
	if (r6.w != 0) {
		r6.xy = r4.xw * screenParams.zw + r6.xy;
		r7.y = depthTexture.Sample(pointSampler_s, r6.xy).x;
		r7.y = invProjParams.z + r7.y;
		r7.y = invProjParams.w / r7.y;
		r8.z = -r7.y;
		r9.xy = uvToViewParams.xy * r6.xy + uvToViewParams.zw;
		r8.xy = r9.xy * r8.zz;
		r8.xyz = r8.xyz + -r0.yzw;
		r7.y = dot(r8.xy, r8.xy);
		r7.y = rsqrt(r7.y);
		r7.y = -r8.z * r7.y;
		r8.x = dot(r8.xyz, r8.xyz);
		r8.y = r8.x < radiusParams.y;
		r8.z = r5.z < r7.y;
		r8.y = r8.z ? r8.y : 0;
		if (r8.y != 0) {
			r8.y = r7.y * r7.y + 1;
			r8.y = rsqrt(r8.y);
			r8.z = r8.y * r7.y;
			r8.x = r8.x * radiusParams.z + 1;
			r8.y = saturate(r7.y * r8.y + -r6.z);
			r7.x = r8.x * r8.y + r7.x;
			r5.z = r7.y;
			r6.z = r8.z;
		}
		r5.w = 3;
	}
	r7.y = r5.w < r1.x;
	r6.w = r6.w ? r7.y : 0;
	if (r6.w != 0) {
		r6.xy = r4.xw * screenParams.zw + r6.xy;
		r7.y = depthTexture.Sample(pointSampler_s, r6.xy).x;
		r7.y = invProjParams.z + r7.y;
		r7.y = invProjParams.w / r7.y;
		r8.z = -r7.y;
		r9.xy = uvToViewParams.xy * r6.xy + uvToViewParams.zw;
		r8.xy = r9.xy * r8.zz;
		r8.xyz = r8.xyz + -r0.yzw;
		r7.y = dot(r8.xy, r8.xy);
		r7.y = rsqrt(r7.y);
		r7.y = -r8.z * r7.y;
		r8.x = dot(r8.xyz, r8.xyz);
		r8.y = r8.x < radiusParams.y;
		r8.z = r5.z < r7.y;
		r8.y = r8.z ? r8.y : 0;
		if (r8.y != 0) {
			r8.y = r7.y * r7.y + 1;
			r8.y = rsqrt(r8.y);
			r8.z = r8.y * r7.y;
			r8.x = r8.x * radiusParams.z + 1;
			r8.y = saturate(r7.y * r8.y + -r6.z);
			r7.x = r8.x * r8.y + r7.x;
			r5.z = r7.y;
			r6.z = r8.z;
		}
		r5.w = 4;
	}
	r5.w = r5.w < r1.x;
	r5.w = r5.w ? r6.w : 0;
	if (r5.w != 0) {
		r4.xw = r4.xw * screenParams.zw + r6.xy;
		r5.w = depthTexture.Sample(pointSampler_s, r4.xw).x;
		r5.w = invProjParams.z + r5.w;
		r5.w = invProjParams.w / r5.w;
		r8.z = -r5.w;
		r4.xw = uvToViewParams.xy * r4.xw + uvToViewParams.zw;
		r8.xy = r4.xw * r8.zz;
		r6.xyw = r8.xyz + -r0.yzw;
		r4.x = dot(r6.xy, r6.xy);
		r4.x = rsqrt(r4.x);
		r4.x = -r6.w * r4.x;
		r4.w = dot(r6.xyw, r6.xyw);
		r5.w = r4.w < radiusParams.y;
		r5.z = r5.z < r4.x;
		r5.z = r5.z ? r5.w : 0;
		if (r5.z != 0) {
			r5.z = r4.x * r4.x + 1;
			r5.z = rsqrt(r5.z);
			r4.w = r4.w * radiusParams.z + 1;
			r4.x = saturate(r4.x * r5.z + -r6.z);
			r7.x = r4.w * r4.x + r7.x;
		}
	}
	r2.w = r7.x + r2.w;
	r6.x = r1.y * -0.707106769 + -r5.y;
	r6.y = r1.z * -0.707106769 + r5.x;
	r4.xw = r6.xy * r4.yz;
	r5.xy = screenParams.zw * r6.xy;
	r5.zw = r4.xw * r1.ww;
	r5.zw = screenParams.xy * r5.zw;
	r5.zw = round(r5.zw);
	r5.zw = r5.zw * screenParams.zw + v1.xy;
	r4.xw = screenParams.xy * r4.xw;
	r4.xw = round(r4.xw);
	r6.xy = screenParams.zw * r4.xw;
	r8.xyz = r6.yyy * r3.xyz;
	r8.xyz = r6.xxx * r2.xyz + r8.xyz;
	r6.z = dot(r8.xy, r8.xy);
	r6.z = rsqrt(r6.z);
	r7.z = -r8.z * r6.z + biasParams.y;
	r5.xy = r1.ww * r6.xy + r5.xy;
	r5.xy = screenParams.xy * r5.xy;
	r5.xy = round(r5.xy);
	r6.xy = screenParams.zw * r5.xy;
	r6.yzw = r6.yyy * r3.xyz;
	r6.xyz = r6.xxx * r2.xyz + r6.yzw;
	r6.x = dot(r6.xy, r6.xy);
	r6.x = rsqrt(r6.x);
	r6.x = -r6.z * r6.x + biasParams.y;
	r6.y = r6.x * r6.x + 1;
	r6.y = rsqrt(r6.y);
	r6.y = r6.x * r6.y;
	r5.xy = r5.xy * screenParams.zw + v1.xy;
	r6.z = depthTexture.Sample(pointSampler_s, r5.xy).x;
	r6.z = invProjParams.z + r6.z;
	r6.z = invProjParams.w / r6.z;
	r8.z = -r6.z;
	r5.xy = uvToViewParams.xy * r5.xy + uvToViewParams.zw;
	r8.xy = r5.xy * r8.zz;
	r8.xyz = r8.xyz + -r0.yzw;
	r5.x = dot(r8.xy, r8.xy);
	r5.x = rsqrt(r5.x);
	r5.x = -r8.z * r5.x;
	r5.y = r5.x * r5.x + 1;
	r5.y = rsqrt(r5.y);
	r6.z = dot(r8.xyz, r8.xyz);
	r6.w = r6.z < radiusParams.y;
	r6.x = r6.x < r5.x;
	r6.x = r6.x ? r6.w : 0;
	r6.z = r6.z * radiusParams.z + 1;
	r5.y = saturate(r5.x * r5.y + -r6.y);
	r7.y = r6.z * r5.y;
	r7.x = max(r7.z, r5.x);
	r5.xy = r6.xx ? r7.xy : r7.zw;
	r6.x = r5.x * r5.x + 1;
	r6.x = rsqrt(r6.x);
	r6.x = r6.x * r5.x;
	if (r3.w != 0) {
		r5.zw = r4.xw * screenParams.zw + r5.zw;
		r6.y = depthTexture.Sample(pointSampler_s, r5.zw).x;
		r6.y = invProjParams.z + r6.y;
		r6.y = invProjParams.w / r6.y;
		r7.z = -r6.y;
		r6.yz = uvToViewParams.xy * r5.zw + uvToViewParams.zw;
		r7.xy = r6.yz * r7.zz;
		r6.yzw = r7.xyz + -r0.yzw;
		r7.x = dot(r6.yz, r6.yz);
		r7.x = rsqrt(r7.x);
		r7.x = r7.x * -r6.w;
		r6.y = dot(r6.yzw, r6.yzw);
		r6.z = r6.y < radiusParams.y;
		r6.w = r5.x < r7.x;
		r6.z = r6.w ? r6.z : 0;
		if (r6.z != 0) {
			r6.z = r7.x * r7.x + 1;
			r6.z = rsqrt(r6.z);
			r6.w = r7.x * r6.z;
			r6.y = r6.y * radiusParams.z + 1;
			r6.z = saturate(r7.x * r6.z + -r6.x);
			r6.y = r6.y * r6.z + r5.y;
			r5.x = r7.x;
			r6.xy = r6.wy;
		} else {
			r6.y = r5.y;
		}
		r5.y = 2;
	} else {
		r6.y = r5.y;
		r5.y = 1;
	}
	r6.z = r5.y < r1.x;
	if (r6.z != 0) {
		r5.zw = r4.xw * screenParams.zw + r5.zw;
		r6.w = depthTexture.Sample(pointSampler_s, r5.zw).x;
		r6.w = invProjParams.z + r6.w;
		r6.w = invProjParams.w / r6.w;
		r7.z = -r6.w;
		r8.xy = uvToViewParams.xy * r5.zw + uvToViewParams.zw;
		r7.xy = r8.xy * r7.zz;
		r7.xyz = r7.xyz + -r0.yzw;
		r6.w = dot(r7.xy, r7.xy);
		r6.w = rsqrt(r6.w);
		r6.w = -r7.z * r6.w;
		r7.x = dot(r7.xyz, r7.xyz);
		r7.y = r7.x < radiusParams.y;
		r7.z = r5.x < r6.w;
		r7.y = r7.z ? r7.y : 0;
		if (r7.y != 0) {
			r7.y = r6.w * r6.w + 1;
			r7.y = rsqrt(r7.y);
			r7.z = r7.y * r6.w;
			r7.x = r7.x * radiusParams.z + 1;
			r7.y = saturate(r6.w * r7.y + -r6.x);
			r6.y = r7.x * r7.y + r6.y;
			r5.x = r6.w;
			r6.x = r7.z;
		}
		r5.y = 3;
	}
	r6.w = r5.y < r1.x;
	r6.z = r6.w ? r6.z : 0;
	if (r6.z != 0) {
		r5.zw = r4.xw * screenParams.zw + r5.zw;
		r6.w = depthTexture.Sample(pointSampler_s, r5.zw).x;
		r6.w = invProjParams.z + r6.w;
		r6.w = invProjParams.w / r6.w;
		r7.z = -r6.w;
		r8.xy = uvToViewParams.xy * r5.zw + uvToViewParams.zw;
		r7.xy = r8.xy * r7.zz;
		r7.xyz = r7.xyz + -r0.yzw;
		r6.w = dot(r7.xy, r7.xy);
		r6.w = rsqrt(r6.w);
		r6.w = -r7.z * r6.w;
		r7.x = dot(r7.xyz, r7.xyz);
		r7.y = r7.x < radiusParams.y;
		r7.z = r5.x < r6.w;
		r7.y = r7.z ? r7.y : 0;
		if (r7.y != 0) {
			r7.y = r6.w * r6.w + 1;
			r7.y = rsqrt(r7.y);
			r7.z = r7.y * r6.w;
			r7.x = r7.x * radiusParams.z + 1;
			r7.y = saturate(r6.w * r7.y + -r6.x);
			r6.y = r7.x * r7.y + r6.y;
			r5.x = r6.w;
			r6.x = r7.z;
		}
		r5.y = 4;
	}
	r5.y = r5.y < r1.x;
	r5.y = r5.y ? r6.z : 0;
	if (r5.y != 0) {
		r4.xw = r4.xw * screenParams.zw + r5.zw;
		r5.y = depthTexture.Sample(pointSampler_s, r4.xw).x;
		r5.y = invProjParams.z + r5.y;
		r5.y = invProjParams.w / r5.y;
		r7.z = -r5.y;
		r4.xw = uvToViewParams.xy * r4.xw + uvToViewParams.zw;
		r7.xy = r4.xw * r7.zz;
		r5.yzw = r7.xyz + -r0.yzw;
		r4.x = dot(r5.yz, r5.yz);
		r4.x = rsqrt(r4.x);
		r4.x = -r5.w * r4.x;
		r4.w = dot(r5.yzw, r5.yzw);
		r5.y = r4.w < radiusParams.y;
		r5.x = r5.x < r4.x;
		r5.x = r5.x ? r5.y : 0;
		if (r5.x != 0) {
			r5.x = r4.x * r4.x + 1;
			r5.x = rsqrt(r5.x);
			r4.w = r4.w * radiusParams.z + 1;
			r4.x = saturate(r4.x * r5.x + -r6.x);
			r6.y = r4.w * r4.x + r6.y;
		}
	}
	r2.w = r6.y + r2.w;
	r5.x = -r1.z * -8.74227766e-08 + -r1.y;
	r5.y = r1.y * -8.74227766e-08 + -r1.z;
	r4.xw = r5.xy * r4.yz;
	r5.zw = r4.xw * r1.ww;
	r5.xyzw = screenParams.zwxy * r5.xyzw;
	r5.zw = round(r5.zw);
	r5.zw = r5.zw * screenParams.zw + v1.xy;
	r4.xw = screenParams.xy * r4.xw;
	r4.xw = round(r4.xw);
	r6.xy = screenParams.zw * r4.xw;
	r7.xyz = r6.yyy * r3.xyz;
	r7.xyz = r6.xxx * r2.xyz + r7.xyz;
	r6.z = dot(r7.xy, r7.xy);
	r6.z = rsqrt(r6.z);
	r7.x = -r7.z * r6.z + biasParams.y;
	r5.xy = r1.ww * r6.xy + r5.xy;
	r5.xy = screenParams.xy * r5.xy;
	r5.xy = round(r5.xy);
	r6.xy = screenParams.zw * r5.xy;
	r6.yzw = r6.yyy * r3.xyz;
	r6.xyz = r6.xxx * r2.xyz + r6.yzw;
	r6.x = dot(r6.xy, r6.xy);
	r6.x = rsqrt(r6.x);
	r6.x = -r6.z * r6.x + biasParams.y;
	r6.y = r6.x * r6.x + 1;
	r6.y = rsqrt(r6.y);
	r6.y = r6.x * r6.y;
	r5.xy = r5.xy * screenParams.zw + v1.xy;
	r6.z = depthTexture.Sample(pointSampler_s, r5.xy).x;
	r6.z = invProjParams.z + r6.z;
	r6.z = invProjParams.w / r6.z;
	r8.z = -r6.z;
	r5.xy = uvToViewParams.xy * r5.xy + uvToViewParams.zw;
	r8.xy = r5.xy * r8.zz;
	r8.xyz = r8.xyz + -r0.yzw;
	r5.x = dot(r8.xy, r8.xy);
	r5.x = rsqrt(r5.x);
	r5.x = -r8.z * r5.x;
	r5.y = r5.x * r5.x + 1;
	r5.y = rsqrt(r5.y);
	r6.z = dot(r8.xyz, r8.xyz);
	r6.w = r6.z < radiusParams.y;
	r6.x = r6.x < r5.x;
	r6.x = r6.x ? r6.w : 0;
	r6.z = r6.z * radiusParams.z + 1;
	r5.y = saturate(r5.x * r5.y + -r6.y);
	r8.y = r6.z * r5.y;
	r8.x = max(r7.x, r5.x);
	r7.yw = float2(0,0);
	r5.xy = r6.xx ? r8.xy : r7.xy;
	r6.x = r5.x * r5.x + 1;
	r6.x = rsqrt(r6.x);
	r6.x = r6.x * r5.x;
	if (r3.w != 0) {
		r5.zw = r4.xw * screenParams.zw + r5.zw;
		r6.y = depthTexture.Sample(pointSampler_s, r5.zw).x;
		r6.y = invProjParams.z + r6.y;
		r6.y = invProjParams.w / r6.y;
		r8.z = -r6.y;
		r6.yz = uvToViewParams.xy * r5.zw + uvToViewParams.zw;
		r8.xy = r6.yz * r8.zz;
		r6.yzw = r8.xyz + -r0.yzw;
		r7.x = dot(r6.yz, r6.yz);
		r7.x = rsqrt(r7.x);
		r7.x = r7.x * -r6.w;
		r6.y = dot(r6.yzw, r6.yzw);
		r6.z = r6.y < radiusParams.y;
		r6.w = r5.x < r7.x;
		r6.z = r6.w ? r6.z : 0;
		if (r6.z != 0) {
			r6.z = r7.x * r7.x + 1;
			r6.z = rsqrt(r6.z);
			r6.w = r7.x * r6.z;
			r6.y = r6.y * radiusParams.z + 1;
			r6.z = saturate(r7.x * r6.z + -r6.x);
			r6.y = r6.y * r6.z + r5.y;
			r5.x = r7.x;
			r6.xy = r6.wy;
		} else {
			r6.y = r5.y;
		}
		r5.y = 2;
	} else {
		r6.y = r5.y;
		r5.y = 1;
	}
	r6.z = r5.y < r1.x;
	if (r6.z != 0) {
		r5.zw = r4.xw * screenParams.zw + r5.zw;
		r6.w = depthTexture.Sample(pointSampler_s, r5.zw).x;
		r6.w = invProjParams.z + r6.w;
		r6.w = invProjParams.w / r6.w;
		r8.z = -r6.w;
		r7.xy = uvToViewParams.xy * r5.zw + uvToViewParams.zw;
		r8.xy = r7.xy * r8.zz;
		r8.xyz = r8.xyz + -r0.yzw;
		r6.w = dot(r8.xy, r8.xy);
		r6.w = rsqrt(r6.w);
		r6.w = -r8.z * r6.w;
		r7.x = dot(r8.xyz, r8.xyz);
		r7.y = r7.x < radiusParams.y;
		r8.x = r5.x < r6.w;
		r7.y = r7.y ? r8.x : 0;
		if (r7.y != 0) {
			r7.y = r6.w * r6.w + 1;
			r7.y = rsqrt(r7.y);
			r8.x = r7.y * r6.w;
			r7.x = r7.x * radiusParams.z + 1;
			r7.y = saturate(r6.w * r7.y + -r6.x);
			r6.y = r7.x * r7.y + r6.y;
			r5.x = r6.w;
			r6.x = r8.x;
		}
		r5.y = 3;
	}
	r6.w = r5.y < r1.x;
	r6.z = r6.w ? r6.z : 0;
	if (r6.z != 0) {
		r5.zw = r4.xw * screenParams.zw + r5.zw;
		r6.w = depthTexture.Sample(pointSampler_s, r5.zw).x;
		r6.w = invProjParams.z + r6.w;
		r6.w = invProjParams.w / r6.w;
		r8.z = -r6.w;
		r7.xy = uvToViewParams.xy * r5.zw + uvToViewParams.zw;
		r8.xy = r7.xy * r8.zz;
		r8.xyz = r8.xyz + -r0.yzw;
		r6.w = dot(r8.xy, r8.xy);
		r6.w = rsqrt(r6.w);
		r6.w = -r8.z * r6.w;
		r7.x = dot(r8.xyz, r8.xyz);
		r7.y = r7.x < radiusParams.y;
		r8.x = r5.x < r6.w;
		r7.y = r7.y ? r8.x : 0;
		if (r7.y != 0) {
			r7.y = r6.w * r6.w + 1;
			r7.y = rsqrt(r7.y);
			r8.x = r7.y * r6.w;
			r7.x = r7.x * radiusParams.z + 1;
			r7.y = saturate(r6.w * r7.y + -r6.x);
			r6.y = r7.x * r7.y + r6.y;
			r5.x = r6.w;
			r6.x = r8.x;
		}
		r5.y = 4;
	}
	r5.y = r5.y < r1.x;
	r5.y = r5.y ? r6.z : 0;
	if (r5.y != 0) {
		r4.xw = r4.xw * screenParams.zw + r5.zw;
		r5.y = depthTexture.Sample(pointSampler_s, r4.xw).x;
		r5.y = invProjParams.z + r5.y;
		r5.y = invProjParams.w / r5.y;
		r8.z = -r5.y;
		r4.xw = uvToViewParams.xy * r4.xw + uvToViewParams.zw;
		r8.xy = r4.xw * r8.zz;
		r5.yzw = r8.xyz + -r0.yzw;
		r4.x = dot(r5.yz, r5.yz);
		r4.x = rsqrt(r4.x);
		r4.x = -r5.w * r4.x;
		r4.w = dot(r5.yzw, r5.yzw);
		r5.y = r4.w < radiusParams.y;
		r5.x = r5.x < r4.x;
		r5.x = r5.x ? r5.y : 0;
		if (r5.x != 0) {
			r5.x = r4.x * r4.x + 1;
			r5.x = rsqrt(r5.x);
			r4.w = r4.w * radiusParams.z + 1;
			r4.x = saturate(r4.x * r5.x + -r6.x);
			r6.y = r4.w * r4.x + r6.y;
		}
	}
	r2.w = r6.y + r2.w;
	r4.x = -0.707106888 * r1.z;
	r5.x = r1.y * -0.70710665 + -r4.x;
	r5.y = dot(r1.zy, float2(-0.70710665,-0.707106888));
	r4.xw = r5.xy * r4.yz;
	r5.zw = r4.xw * r1.ww;
	r5.xyzw = screenParams.zwxy * r5.xyzw;
	r5.zw = round(r5.zw);
	r5.zw = r5.zw * screenParams.zw + v1.xy;
	r4.xw = screenParams.xy * r4.xw;
	r4.xw = round(r4.xw);
	r6.xy = screenParams.zw * r4.xw;
	r8.xyz = r6.yyy * r3.xyz;
	r8.xyz = r6.xxx * r2.xyz + r8.xyz;
	r6.z = dot(r8.xy, r8.xy);
	r6.z = rsqrt(r6.z);
	r7.z = -r8.z * r6.z + biasParams.y;
	r5.xy = r1.ww * r6.xy + r5.xy;
	r5.xy = screenParams.xy * r5.xy;
	r5.xy = round(r5.xy);
	r6.xy = screenParams.zw * r5.xy;
	r6.yzw = r6.yyy * r3.xyz;
	r6.xyz = r6.xxx * r2.xyz + r6.yzw;
	r6.x = dot(r6.xy, r6.xy);
	r6.x = rsqrt(r6.x);
	r6.x = -r6.z * r6.x + biasParams.y;
	r6.y = r6.x * r6.x + 1;
	r6.y = rsqrt(r6.y);
	r6.y = r6.x * r6.y;
	r5.xy = r5.xy * screenParams.zw + v1.xy;
	r6.z = depthTexture.Sample(pointSampler_s, r5.xy).x;
	r6.z = invProjParams.z + r6.z;
	r6.z = invProjParams.w / r6.z;
	r8.z = -r6.z;
	r5.xy = uvToViewParams.xy * r5.xy + uvToViewParams.zw;
	r8.xy = r5.xy * r8.zz;
	r8.xyz = r8.xyz + -r0.yzw;
	r5.x = dot(r8.xy, r8.xy);
	r5.x = rsqrt(r5.x);
	r5.x = -r8.z * r5.x;
	r5.y = r5.x * r5.x + 1;
	r5.y = rsqrt(r5.y);
	r6.z = dot(r8.xyz, r8.xyz);
	r6.w = r6.z < radiusParams.y;
	r6.x = r6.x < r5.x;
	r6.x = r6.x ? r6.w : 0;
	r6.z = r6.z * radiusParams.z + 1;
	r5.y = saturate(r5.x * r5.y + -r6.y);
	r7.y = r6.z * r5.y;
	r7.x = max(r7.z, r5.x);
	r5.xy = r6.xx ? r7.xy : r7.zw;
	r6.x = r5.x * r5.x + 1;
	r6.x = rsqrt(r6.x);
	r6.x = r6.x * r5.x;
	if (r3.w != 0) {
		r5.zw = r4.xw * screenParams.zw + r5.zw;
		r6.y = depthTexture.Sample(pointSampler_s, r5.zw).x;
		r6.y = invProjParams.z + r6.y;
		r6.y = invProjParams.w / r6.y;
		r7.z = -r6.y;
		r6.yz = uvToViewParams.xy * r5.zw + uvToViewParams.zw;
		r7.xy = r6.yz * r7.zz;
		r6.yzw = r7.xyz + -r0.yzw;
		r7.x = dot(r6.yz, r6.yz);
		r7.x = rsqrt(r7.x);
		r7.x = r7.x * -r6.w;
		r6.y = dot(r6.yzw, r6.yzw);
		r6.z = r6.y < radiusParams.y;
		r6.w = r5.x < r7.x;
		r6.z = r6.w ? r6.z : 0;
		if (r6.z != 0) {
			r6.z = r7.x * r7.x + 1;
			r6.z = rsqrt(r6.z);
			r6.w = r7.x * r6.z;
			r6.y = r6.y * radiusParams.z + 1;
			r6.z = saturate(r7.x * r6.z + -r6.x);
			r6.y = r6.y * r6.z + r5.y;
			r5.x = r7.x;
			r6.xy = r6.wy;
		} else {
			r6.y = r5.y;
		}
		r5.y = 2;
	} else {
		r6.y = r5.y;
		r5.y = 1;
	}
	r6.z = r5.y < r1.x;
	if (r6.z != 0) {
		r5.zw = r4.xw * screenParams.zw + r5.zw;
		r6.w = depthTexture.Sample(pointSampler_s, r5.zw).x;
		r6.w = invProjParams.z + r6.w;
		r6.w = invProjParams.w / r6.w;
		r7.z = -r6.w;
		r8.xy = uvToViewParams.xy * r5.zw + uvToViewParams.zw;
		r7.xy = r8.xy * r7.zz;
		r7.xyz = r7.xyz + -r0.yzw;
		r6.w = dot(r7.xy, r7.xy);
		r6.w = rsqrt(r6.w);
		r6.w = -r7.z * r6.w;
		r7.x = dot(r7.xyz, r7.xyz);
		r7.y = r7.x < radiusParams.y;
		r7.z = r5.x < r6.w;
		r7.y = r7.z ? r7.y : 0;
		if (r7.y != 0) {
			r7.y = r6.w * r6.w + 1;
			r7.y = rsqrt(r7.y);
			r7.z = r7.y * r6.w;
			r7.x = r7.x * radiusParams.z + 1;
			r7.y = saturate(r6.w * r7.y + -r6.x);
			r6.y = r7.x * r7.y + r6.y;
			r5.x = r6.w;
			r6.x = r7.z;
		}
		r5.y = 3;
	}
	r6.w = r5.y < r1.x;
	r6.z = r6.w ? r6.z : 0;
	if (r6.z != 0) {
		r5.zw = r4.xw * screenParams.zw + r5.zw;
		r6.w = depthTexture.Sample(pointSampler_s, r5.zw).x;
		r6.w = invProjParams.z + r6.w;
		r6.w = invProjParams.w / r6.w;
		r7.z = -r6.w;
		r8.xy = uvToViewParams.xy * r5.zw + uvToViewParams.zw;
		r7.xy = r8.xy * r7.zz;
		r7.xyz = r7.xyz + -r0.yzw;
		r6.w = dot(r7.xy, r7.xy);
		r6.w = rsqrt(r6.w);
		r6.w = -r7.z * r6.w;
		r7.x = dot(r7.xyz, r7.xyz);
		r7.y = r7.x < radiusParams.y;
		r7.z = r5.x < r6.w;
		r7.y = r7.z ? r7.y : 0;
		if (r7.y != 0) {
			r7.y = r6.w * r6.w + 1;
			r7.y = rsqrt(r7.y);
			r7.z = r7.y * r6.w;
			r7.x = r7.x * radiusParams.z + 1;
			r7.y = saturate(r6.w * r7.y + -r6.x);
			r6.y = r7.x * r7.y + r6.y;
			r5.x = r6.w;
			r6.x = r7.z;
		}
		r5.y = 4;
	}
	r5.y = r5.y < r1.x;
	r5.y = r5.y ? r6.z : 0;
	if (r5.y != 0) {
		r4.xw = r4.xw * screenParams.zw + r5.zw;
		r5.y = depthTexture.Sample(pointSampler_s, r4.xw).x;
		r5.y = invProjParams.z + r5.y;
		r5.y = invProjParams.w / r5.y;
		r7.z = -r5.y;
		r4.xw = uvToViewParams.xy * r4.xw + uvToViewParams.zw;
		r7.xy = r4.xw * r7.zz;
		r5.yzw = r7.xyz + -r0.yzw;
		r4.x = dot(r5.yz, r5.yz);
		r4.x = rsqrt(r4.x);
		r4.x = -r5.w * r4.x;
		r4.w = dot(r5.yzw, r5.yzw);
		r5.y = r4.w < radiusParams.y;
		r5.x = r5.x < r4.x;
		r5.x = r5.x ? r5.y : 0;
		if (r5.x != 0) {
			r5.x = r4.x * r4.x + 1;
			r5.x = rsqrt(r5.x);
			r4.w = r4.w * radiusParams.z + 1;
			r4.x = saturate(r4.x * r5.x + -r6.x);
			r6.y = r4.w * r4.x + r6.y;
		}
	}
	r2.w = r6.y + r2.w;
	r5.x = r1.y * 1.19248806e-08 + r1.z;
	r5.y = r1.z * 1.19248806e-08 + -r1.y;
	r4.xw = r5.xy * r4.yz;
	r5.zw = r4.xw * r1.ww;
	r5.xyzw = screenParams.zwxy * r5.xyzw;
	r5.zw = round(r5.zw);
	r5.zw = r5.zw * screenParams.zw + v1.xy;
	r4.xw = screenParams.xy * r4.xw;
	r4.xw = round(r4.xw);
	r6.xy = screenParams.zw * r4.xw;
	r7.xyz = r6.yyy * r3.xyz;
	r7.xyz = r6.xxx * r2.xyz + r7.xyz;
	r6.z = dot(r7.xy, r7.xy);
	r6.z = rsqrt(r6.z);
	r7.x = -r7.z * r6.z + biasParams.y;
	r5.xy = r1.ww * r6.xy + r5.xy;
	r5.xy = screenParams.xy * r5.xy;
	r5.xy = round(r5.xy);
	r6.xy = screenParams.zw * r5.xy;
	r6.yzw = r6.yyy * r3.xyz;
	r6.xyz = r6.xxx * r2.xyz + r6.yzw;
	r6.x = dot(r6.xy, r6.xy);
	r6.x = rsqrt(r6.x);
	r6.x = -r6.z * r6.x + biasParams.y;
	r6.y = r6.x * r6.x + 1;
	r6.y = rsqrt(r6.y);
	r6.y = r6.x * r6.y;
	r5.xy = r5.xy * screenParams.zw + v1.xy;
	r6.z = depthTexture.Sample(pointSampler_s, r5.xy).x;
	r6.z = invProjParams.z + r6.z;
	r6.z = invProjParams.w / r6.z;
	r8.z = -r6.z;
	r5.xy = uvToViewParams.xy * r5.xy + uvToViewParams.zw;
	r8.xy = r5.xy * r8.zz;
	r8.xyz = r8.xyz + -r0.yzw;
	r5.x = dot(r8.xy, r8.xy);
	r5.x = rsqrt(r5.x);
	r5.x = -r8.z * r5.x;
	r5.y = r5.x * r5.x + 1;
	r5.y = rsqrt(r5.y);
	r6.z = dot(r8.xyz, r8.xyz);
	r6.w = r6.z < radiusParams.y;
	r6.x = r6.x < r5.x;
	r6.x = r6.x ? r6.w : 0;
	r6.z = r6.z * radiusParams.z + 1;
	r5.y = saturate(r5.x * r5.y + -r6.y);
	r8.y = r6.z * r5.y;
	r8.x = max(r7.x, r5.x);
	r7.yw = float2(0,0);
	r5.xy = r6.xx ? r8.xy : r7.xy;
	r6.x = r5.x * r5.x + 1;
	r6.x = rsqrt(r6.x);
	r6.x = r6.x * r5.x;
	if (r3.w != 0) {
		r5.zw = r4.xw * screenParams.zw + r5.zw;
		r6.y = depthTexture.Sample(pointSampler_s, r5.zw).x;
		r6.y = invProjParams.z + r6.y;
		r6.y = invProjParams.w / r6.y;
		r8.z = -r6.y;
		r6.yz = uvToViewParams.xy * r5.zw + uvToViewParams.zw;
		r8.xy = r6.yz * r8.zz;
		r6.yzw = r8.xyz + -r0.yzw;
		r7.x = dot(r6.yz, r6.yz);
		r7.x = rsqrt(r7.x);
		r7.x = r7.x * -r6.w;
		r6.y = dot(r6.yzw, r6.yzw);
		r6.z = r6.y < radiusParams.y;
		r6.w = r5.x < r7.x;
		r6.z = r6.w ? r6.z : 0;
		if (r6.z != 0) {
			r6.z = r7.x * r7.x + 1;
			r6.z = rsqrt(r6.z);
			r6.w = r7.x * r6.z;
			r6.y = r6.y * radiusParams.z + 1;
			r6.z = saturate(r7.x * r6.z + -r6.x);
			r6.y = r6.y * r6.z + r5.y;
			r5.x = r7.x;
			r6.xy = r6.wy;
		} else {
			r6.y = r5.y;
		}
		r5.y = 2;
	} else {
		r6.y = r5.y;
		r5.y = 1;
	}
	r6.z = r5.y < r1.x;
	if (r6.z != 0) {
		r5.zw = r4.xw * screenParams.zw + r5.zw;
		r6.w = depthTexture.Sample(pointSampler_s, r5.zw).x;
		r6.w = invProjParams.z + r6.w;
		r6.w = invProjParams.w / r6.w;
		r8.z = -r6.w;
		r7.xy = uvToViewParams.xy * r5.zw + uvToViewParams.zw;
		r8.xy = r7.xy * r8.zz;
		r8.xyz = r8.xyz + -r0.yzw;
		r6.w = dot(r8.xy, r8.xy);
		r6.w = rsqrt(r6.w);
		r6.w = -r8.z * r6.w;
		r7.x = dot(r8.xyz, r8.xyz);
		r7.y = r7.x < radiusParams.y;
		r8.x = r5.x < r6.w;
		r7.y = r7.y ? r8.x : 0;
		if (r7.y != 0) {
			r7.y = r6.w * r6.w + 1;
			r7.y = rsqrt(r7.y);
			r8.x = r7.y * r6.w;
			r7.x = r7.x * radiusParams.z + 1;
			r7.y = saturate(r6.w * r7.y + -r6.x);
			r6.y = r7.x * r7.y + r6.y;
			r5.x = r6.w;
			r6.x = r8.x;
		}
		r5.y = 3;
	}
	r6.w = r5.y < r1.x;
	r6.z = r6.w ? r6.z : 0;
	if (r6.z != 0) {
		r5.zw = r4.xw * screenParams.zw + r5.zw;
		r6.w = depthTexture.Sample(pointSampler_s, r5.zw).x;
		r6.w = invProjParams.z + r6.w;
		r6.w = invProjParams.w / r6.w;
		r8.z = -r6.w;
		r7.xy = uvToViewParams.xy * r5.zw + uvToViewParams.zw;
		r8.xy = r7.xy * r8.zz;
		r8.xyz = r8.xyz + -r0.yzw;
		r6.w = dot(r8.xy, r8.xy);
		r6.w = rsqrt(r6.w);
		r6.w = -r8.z * r6.w;
		r7.x = dot(r8.xyz, r8.xyz);
		r7.y = r7.x < radiusParams.y;
		r8.x = r5.x < r6.w;
		r7.y = r7.y ? r8.x : 0;
		if (r7.y != 0) {
			r7.y = r6.w * r6.w + 1;
			r7.y = rsqrt(r7.y);
			r8.x = r7.y * r6.w;
			r7.x = r7.x * radiusParams.z + 1;
			r7.y = saturate(r6.w * r7.y + -r6.x);
			r6.y = r7.x * r7.y + r6.y;
			r5.x = r6.w;
			r6.x = r8.x;
		}
		r5.y = 4;
	}
	r5.y = r5.y < r1.x;
	r5.y = r5.y ? r6.z : 0;
	if (r5.y != 0) {
		r4.xw = r4.xw * screenParams.zw + r5.zw;
		r5.y = depthTexture.Sample(pointSampler_s, r4.xw).x;
		r5.y = invProjParams.z + r5.y;
		r5.y = invProjParams.w / r5.y;
		r8.z = -r5.y;
		r4.xw = uvToViewParams.xy * r4.xw + uvToViewParams.zw;
		r8.xy = r4.xw * r8.zz;
		r5.yzw = r8.xyz + -r0.yzw;
		r4.x = dot(r5.yz, r5.yz);
		r4.x = rsqrt(r4.x);
		r4.x = -r5.w * r4.x;
		r4.w = dot(r5.yzw, r5.yzw);
		r5.y = r4.w < radiusParams.y;
		r5.x = r5.x < r4.x;
		r5.x = r5.x ? r5.y : 0;
		if (r5.x != 0) {
			r5.x = r4.x * r4.x + 1;
			r5.x = rsqrt(r5.x);
			r4.w = r4.w * radiusParams.z + 1;
			r4.x = saturate(r4.x * r5.x + -r6.x);
			r6.y = r4.w * r4.x + r6.y;
		}
	}
	r2.w = r6.y + r2.w;
	r4.x = -0.707106531 * r1.z;
	r5.x = r1.y * 0.707107008 + -r4.x;
	r5.y = dot(r1.zy, float2(0.707107008,-0.707106531));
	r1.yz = r5.xy * r4.yz;
	r4.xy = screenParams.zw * r5.xy;
	r4.zw = r1.ww * r1.yz;
	r4.zw = screenParams.xy * r4.zw;
	r4.zw = round(r4.zw);
	r4.zw = r4.zw * screenParams.zw + v1.xy;
	r1.yz = screenParams.xy * r1.yz;
	r1.yz = round(r1.yz);
	r5.xy = screenParams.zw * r1.yz;
	r6.xyz = r5.yyy * r3.xyz;
	r6.xyz = r5.xxx * r2.xyz + r6.xyz;
	r5.z = dot(r6.xy, r6.xy);
	r5.z = rsqrt(r5.z);
	r7.z = -r6.z * r5.z + biasParams.y;
	r4.xy = r1.ww * r5.xy + r4.xy;
	r4.xy = screenParams.xy * r4.xy;
	r4.xy = round(r4.xy);
	r5.xy = screenParams.zw * r4.xy;
	r3.xyz = r5.yyy * r3.xyz;
	r2.xyz = r5.xxx * r2.xyz + r3.xyz;
	r1.w = dot(r2.xy, r2.xy);
	r1.w = rsqrt(r1.w);
	r1.w = -r2.z * r1.w + biasParams.y;
	r2.x = r1.w * r1.w + 1;
	r2.x = rsqrt(r2.x);
	r2.x = r2.x * r1.w;
	r2.yz = r4.xy * screenParams.zw + v1.xy;
	r3.x = depthTexture.Sample(pointSampler_s, r2.yz).x;
	r3.x = invProjParams.z + r3.x;
	r3.x = invProjParams.w / r3.x;
	r3.z = -r3.x;
	r2.yz = uvToViewParams.xy * r2.yz + uvToViewParams.zw;
	r3.xy = r2.yz * r3.zz;
	r3.xyz = r3.xyz + -r0.yzw;
	r2.y = dot(r3.xy, r3.xy);
	r2.y = rsqrt(r2.y);
	r2.y = -r3.z * r2.y;
	r2.z = r2.y * r2.y + 1;
	r2.z = rsqrt(r2.z);
	r3.x = dot(r3.xyz, r3.xyz);
	r3.y = r3.x < radiusParams.y;
	r1.w = r1.w < r2.y;
	r1.w = r1.w ? r3.y : 0;
	r3.x = r3.x * radiusParams.z + 1;
	r2.x = saturate(r2.y * r2.z + -r2.x);
	r3.y = r3.x * r2.x;
	r3.x = max(r7.z, r2.y);
	r2.xy = r1.ww ? r3.xy : r7.zw;
	r1.w = r2.x * r2.x + 1;
	r1.w = rsqrt(r1.w);
	r1.w = r2.x * r1.w;
	if (r3.w != 0) {
		r4.zw = r1.yz * screenParams.zw + r4.zw;
		r2.z = depthTexture.Sample(pointSampler_s, r4.zw).x;
		r2.z = invProjParams.z + r2.z;
		r2.z = invProjParams.w / r2.z;
		r3.z = -r2.z;
		r4.xy = uvToViewParams.xy * r4.zw + uvToViewParams.zw;
		r3.xy = r4.xy * r3.zz;
		r3.xyz = r3.xyz + -r0.yzw;
		r2.z = dot(r3.xy, r3.xy);
		r2.z = rsqrt(r2.z);
		r2.z = -r3.z * r2.z;
		r3.x = dot(r3.xyz, r3.xyz);
		r3.y = r3.x < radiusParams.y;
		r3.z = r2.x < r2.z;
		r3.y = r3.z ? r3.y : 0;
		if (r3.y != 0) {
			r3.y = r2.z * r2.z + 1;
			r3.y = rsqrt(r3.y);
			r3.z = r3.y * r2.z;
			r3.x = r3.x * radiusParams.z + 1;
			r3.y = saturate(r2.z * r3.y + -r1.w);
			r3.x = r3.x * r3.y + r2.y;
			r2.x = r2.z;
			r1.w = r3.z;
		} else {
			r3.x = r2.y;
		}
		r2.y = 2;
	} else {
		r3.x = r2.y;
		r2.y = 1;
	}
	r2.z = r2.y < r1.x;
	if (r2.z != 0) {
		r4.zw = r1.yz * screenParams.zw + r4.zw;
		r3.y = depthTexture.Sample(pointSampler_s, r4.zw).x;
		r3.y = invProjParams.z + r3.y;
		r3.y = invProjParams.w / r3.y;
		r5.z = -r3.y;
		r3.yz = uvToViewParams.xy * r4.zw + uvToViewParams.zw;
		r5.xy = r3.yz * r5.zz;
		r3.yzw = r5.xyz + -r0.yzw;
		r4.x = dot(r3.yz, r3.yz);
		r4.x = rsqrt(r4.x);
		r4.x = r4.x * -r3.w;
		r3.y = dot(r3.yzw, r3.yzw);
		r3.z = r3.y < radiusParams.y;
		r3.w = r2.x < r4.x;
		r3.z = r3.w ? r3.z : 0;
		if (r3.z != 0) {
			r3.z = r4.x * r4.x + 1;
			r3.z = rsqrt(r3.z);
			r3.w = r4.x * r3.z;
			r3.y = r3.y * radiusParams.z + 1;
			r3.z = saturate(r4.x * r3.z + -r1.w);
			r3.x = r3.y * r3.z + r3.x;
			r2.x = r4.x;
			r1.w = r3.w;
		}
		r2.y = 3;
	}
	r3.y = r2.y < r1.x;
	r2.z = r2.z ? r3.y : 0;
	if (r2.z != 0) {
		r4.zw = r1.yz * screenParams.zw + r4.zw;
		r3.y = depthTexture.Sample(pointSampler_s, r4.zw).x;
		r3.y = invProjParams.z + r3.y;
		r3.y = invProjParams.w / r3.y;
		r5.z = -r3.y;
		r3.yz = uvToViewParams.xy * r4.zw + uvToViewParams.zw;
		r5.xy = r3.yz * r5.zz;
		r3.yzw = r5.xyz + -r0.yzw;
		r4.x = dot(r3.yz, r3.yz);
		r4.x = rsqrt(r4.x);
		r4.x = r4.x * -r3.w;
		r3.y = dot(r3.yzw, r3.yzw);
		r3.z = r3.y < radiusParams.y;
		r3.w = r2.x < r4.x;
		r3.z = r3.w ? r3.z : 0;
		if (r3.z != 0) {
			r3.z = r4.x * r4.x + 1;
			r3.z = rsqrt(r3.z);
			r3.w = r4.x * r3.z;
			r3.y = r3.y * radiusParams.z + 1;
			r3.z = saturate(r4.x * r3.z + -r1.w);
			r3.x = r3.y * r3.z + r3.x;
			r2.x = r4.x;
			r1.w = r3.w;
		}
		r2.y = 4;
	}
	r1.x = r2.y < r1.x;
	r1.x = r1.x ? r2.z : 0;
	if (r1.x != 0) {
		r1.xy = r1.yz * screenParams.zw + r4.zw;
		r1.z = depthTexture.Sample(pointSampler_s, r1.xy).x;
		r1.z = invProjParams.z + r1.z;
		r1.z = invProjParams.w / r1.z;
		r4.z = -r1.z;
		r1.xy = uvToViewParams.xy * r1.xy + uvToViewParams.zw;
		r4.xy = r1.xy * r4.zz;
		r1.xyz = r4.xyz + -r0.yzw;
		r0.y = dot(r1.xy, r1.xy);
		r0.y = rsqrt(r0.y);
		r0.y = -r1.z * r0.y;
		r0.z = dot(r1.xyz, r1.xyz);
		r1.x = r0.z < radiusParams.y;
		r1.y = r2.x < r0.y;
		r1.x = r1.y ? r1.x : 0;
		if (r1.x != 0) {
			r1.x = r0.y * r0.y + 1;
			r1.x = rsqrt(r1.x);
			r0.z = r0.z * radiusParams.z + 1;
			r0.y = saturate(r0.y * r1.x + -r1.w);
			r3.x = r0.z * r0.y + r3.x;
		}
	}
	r0.y = r3.x + r2.w;
	r0.y = biasParams.z * r0.y;
	r0.x = saturate(-r0.y * 0.125 + 1);
	o0.xy = r0.xw;
	return;
}