// ---- Created with 3Dmigoto v1.3.16 on Thu Jul 16 19:31:41 2026
Texture2DArray<float4> t3 : register(t3);

Texture2D<float4> t2 : register(t2);

Texture2D<float4> t1 : register(t1);

Texture2D<float4> t0 : register(t0);

SamplerState s2_s : register(s2);

SamplerState s1_s : register(s1);

SamplerState s0_s : register(s0);

cbuffer cb2 : register(b2)
{
  float4 cb2[53];
}

cbuffer cb3 : register(b3)
{
  float4 cb3[6];
}

cbuffer cb1 : register(b1)
{
  float4 cb1[2];
}

#if FIRE_RETUNED == 0
LET_THIS_BREAK
#endif

// 3Dmigoto declarations
#define cmp -
#include "./common.hlsl"


void main(
  float4 v0 : SV_POSITION0,
  float4 v1 : TEXCOORD0,
  float4 v2 : TEXCOORD2,
  float4 v3 : TEXCOORD1,
  float4 v4 : COLOR0,
  uint v5 : SV_IsFrontFace0,
  out float4 o0 : SV_Target0)
{
  float4 r0,r1;
  uint4 bitmask, uiDest;
  float4 fDest;

  r0.xy = cb3[3].xy * cb1[1].xx;
  r0.xy = v1.xy * cb3[2].zw + r0.xy;
  r0.xy = t0.Sample(s0_s, r0.xy).yw;
  
  r0.xy = r0.xy * float2(2,2) + float2(-1,-1);
  r0.z = -r0.y;
  r0.xy = r0.xz * cb3[3].zz + v1.xy;
  r1.x = cb3[3].w * r0.x;
  r1.y = cb3[4].x * r0.y;
  r0.xyzw = t1.Sample(s1_s, r0.xy).xyzw; //controls color

  r1.xy = cb1[1].xx * cb3[4].yz + r1.xy; //cb1[1].xxxx, cb3[4].yzyy, r1.xyxx
  r1.xyzw = t2.Sample(s1_s, r1.xy).xyzw;

  r0.xyzw = r1.xyzw * r0.xyzw;
  r0.xy = cb3[1].xy * r0.xy;
  r0.x = r0.x + r0.y;
  r0.x = cb3[1].z * r0.z + r0.x;
  r0.x = v4.w * r0.x;
  r0.x = r0.x * r0.w;
  r1.x = r0.x * cb3[4].w + cb3[0].w;
  r0.x = log2(r0.x);
  r0.x = cb3[5].z * r0.x;
  r0.x = exp2(r0.x);
  r0.y = cmp(cb3[5].x < 0.5);
  r1.z = r0.y ? cb3[5].y : 2;
  r1.y = 0;
    r1.x = FireTonemap(r1.x, FIRE_PEAK, 0.90);
  r0.yzw = t3.SampleLevel(s2_s, r1.xyz, 0).xyz;
    r0.yzw *= FIRE_BOOST * 0.67;
  r0.yzw = cb3[0].xyz * r0.yzw;
  r0.xyz = r0.yzw * r0.xxx;
  r0.w = !cb3[2].y ? cb2[24].w : 1;
  r0.xyz = r0.xyz * r0.www;
  r0.xyz = cb3[5].www * r0.xyz;
  r1.xyz = cb2[26].www * r0.xyz;
  r0.xyz = !cb3[2].yyy ? r1.xyz : r0.xyz;
  o0.xyz = v2.www * r0.xyz;
  o0.w = 0;
  return;
}

/*
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
// TEXCOORD                 2   xyzw        2     NONE   float      w
// TEXCOORD                 1   xyzw        3     NONE   float       
// COLOR                    0   xyzw        4     NONE   float      w
// SV_IsFrontFace           0   x           5    FFACE    uint       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      0x00000000: ps_5_0
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_constantbuffer CB1[2], immediateIndexed
      0x0000001C: dcl_constantbuffer CB3[6], immediateIndexed
      0x0000002C: dcl_constantbuffer CB2[53], immediateIndexed
      0x0000003C: dcl_sampler s0, mode_default
      0x00000048: dcl_sampler s1, mode_default
      0x00000054: dcl_sampler s2, mode_default
      0x00000060: dcl_resource_texture2d (float,float,float,float) t0
      0x00000070: dcl_resource_texture2d (float,float,float,float) t1
      0x00000080: dcl_resource_texture2d (float,float,float,float) t2
      0x00000090: dcl_resource_texture2darray (float,float,float,float) t3
      0x000000A0: dcl_input_ps linear v1.xy
      0x000000AC: dcl_input_ps linear v2.w
      0x000000B8: dcl_input_ps linear v4.w
      0x000000C4: dcl_output o0.xyzw
      0x000000D0: dcl_temps 2
   0  0x000000D8: mul r0.xy, cb1[1].xxxx, cb3[3].xyxx
   1  0x000000FC: mad r0.xy, v1.xyxx, cb3[2].zwzz, r0.xyxx
   2  0x00000124: sample_indexable(texture2d)(float,float,float,float) r0.xy, r0.xyxx, t0.ywxz, s0
   3  0x00000150: mad r0.xy, r0.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
   4  0x0000018C: mov r0.z, -r0.y
   5  0x000001A4: mad r0.xy, r0.xzxx, cb3[3].zzzz, v1.xyxx
   6  0x000001CC: mul r1.x, r0.x, cb3[3].w
   7  0x000001EC: mul r1.y, r0.y, cb3[4].x
   8  0x0000020C: sample_indexable(texture2d)(float,float,float,float) r0.xyzw, r0.xyxx, t1.xyzw, s1
   9  0x00000238: mad r1.xy, cb1[1].xxxx, cb3[4].yzyy, r1.xyxx
  10  0x00000264: sample_indexable(texture2d)(float,float,float,float) r1.xyzw, r1.xyxx, t2.xyzw, s1
  11  0x00000290: mul r0.xyzw, r0.xyzw, r1.xyzw
  12  0x000002AC: mul r0.xy, r0.xyxx, cb3[1].xyxx
  13  0x000002CC: add r0.x, r0.y, r0.x
  14  0x000002E8: mad r0.x, cb3[1].z, r0.z, r0.x
  15  0x00000310: mul r0.x, r0.x, v4.w
  16  0x0000032C: mul r0.x, r0.w, r0.x
  17  0x00000348: mad r1.x, r0.x, cb3[4].w, cb3[0].w
  18  0x00000374: log r0.x, r0.x
  19  0x00000388: mul r0.x, r0.x, cb3[5].z
  20  0x000003A8: exp r0.x, r0.x
  21  0x000003BC: lt r0.y, cb3[5].x, l(0.500000)
  22  0x000003DC: movc r1.z, r0.y, cb3[5].y, l(2.000000)
  23  0x00000404: mov r1.y, l(0)
  24  0x00000418: sample_l_indexable(texture2darray)(float,float,float,float) r0.yzw, r1.xyzx, t3.wxyz, s2, l(0.000000)
  25  0x0000044C: mul r0.yzw, r0.yyzw, cb3[0].xxyz
  26  0x0000046C: mul r0.xyz, r0.xxxx, r0.yzwy
  27  0x00000488: movc r0.w, cb3[2].y, cb2[24].w, l(1.000000)
  28  0x000004B4: mul r0.xyz, r0.wwww, r0.xyzx
  29  0x000004D0: mul r0.xyz, r0.xyzx, cb3[5].wwww
  30  0x000004F0: mul r1.xyz, r0.xyzx, cb2[26].wwww
  31  0x00000510: movc r0.xyz, cb3[2].yyyy, r1.xyzx, r0.xyzx
  32  0x00000538: mul o0.xyz, r0.xyzx, v2.wwww
  33  0x00000554: mov o0.w, l(0)
  34  0x00000568: ret 
// Approximately 0 instruction slots used

*/