// ---- Created with 3Dmigoto v1.3.16 on Thu Jul 16 19:31:30 2026
Texture2DArray<float4> t2 : register(t2);

Texture2D<float4> t1 : register(t1);

Texture2DArray<float4> t0 : register(t0);

SamplerState s2_s : register(s2);

SamplerState s1_s : register(s1);

SamplerState s0_s : register(s0);

cbuffer cb2 : register(b2)
{
  float4 cb2[53];
}

cbuffer cb3 : register(b3)
{
  float4 cb3[10];
}

// 3Dmigoto declarations
#define cmp -
#include "./common.hlsl"
#if FIRE_RETUNED == 0
LET_THIS_BREAK
#endif

void main(
  float4 v0 : SV_POSITION0,
  float4 v1 : TEXCOORD0,
  float4 v2 : TEXCOORD2,
  float4 v3 : TEXCOORD1,
  float4 v4 : COLOR0,
  uint v5 : SV_IsFrontFace0,
  out float4 o0 : SV_Target0)
{
  float4 r0,r1;
  uint4 bitmask, uiDest;
  float4 fDest;

  r0.xy = v3.xy / v3.ww;
  r0.xy = min(cb2[22].zw, r0.xy);
  r0.x = t1.Sample(s2_s, r0.xy).x;
  r0.x = v3.w + -r0.x;
  r0.x = saturate(abs(r0.x) / cb3[7].w);
  r0.x = 1 + -r0.x;
  r0.x = log2(r0.x);
  r0.x = cb3[8].x * r0.x;
  r0.x = exp2(r0.x);
  r0.x = 1 + -r0.x;
  r0.x = max(0, r0.x);
  r1.xyzw = t0.Sample(s1_s, v1.xyz).xyzw;
  r0.yz = cb3[2].xy * r1.xy;
  r0.y = r0.y + r0.z;
  r0.y = cb3[2].z * r1.z + r0.y;
  r0.y = cb3[2].w * r1.w + r0.y;
  r0.y = v4.w * r0.y;
  r0.x = r0.y * r0.x;
  r1.x = r0.x * cb3[8].y + cb3[1].x;
  r0.x = log2(r0.x);
  r0.x = cb3[9].x * r0.x;
  o0.w = exp2(r0.x);
  r0.x = cb3[8].z + v4.x;
  r0.x = cmp(r0.x < 0.5);
  r1.z = r0.x ? cb3[8].w : 2; //bow aim turns blue
  r1.y = 0;
    r1.x = FireTonemap(r1.x, FIRE_PEAK);
  r0.xyz = t2.SampleLevel(s0_s, r1.xyz, 0).xyz;
    r0.xyz *= FIRE_BOOST;
  r0.xyz = cb3[0].yzw * r0.xyz;
  r0.w = !cb3[0].x ? cb2[24].w : 1; //TODO: these selects are not decompiled right?
  r0.xyz = r0.www * r0.xyz;
  r1.xyz = cb2[26].www * r0.xyz;
  o0.xyz = !cb3[0].xxx ? r1.xyz : r0.xyz; //TODO: these selects are not decompiled right?
    // o0.xyz *= 8;
  return;
}

/*
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xyz         1     NONE   float   xyz 
// TEXCOORD                 2   xyzw        2     NONE   float       
// TEXCOORD                 1   xyzw        3     NONE   float   xy w
// COLOR                    0   xyzw        4     NONE   float   x  w
// SV_IsFrontFace           0   x           5    FFACE    uint       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      0x00000000: ps_5_0
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_constantbuffer CB3[10], immediateIndexed
      0x0000001C: dcl_constantbuffer CB2[53], immediateIndexed
      0x0000002C: dcl_sampler s0, mode_default
      0x00000038: dcl_sampler s1, mode_default
      0x00000044: dcl_sampler s2, mode_default
      0x00000050: dcl_resource_texture2darray (float,float,float,float) t0
      0x00000060: dcl_resource_texture2d (float,float,float,float) t1
      0x00000070: dcl_resource_texture2darray (float,float,float,float) t2
      0x00000080: dcl_input_ps linear v1.xyz
      0x0000008C: dcl_input_ps linear v3.xyw
      0x00000098: dcl_input_ps linear v4.xw
      0x000000A4: dcl_output o0.xyzw
      0x000000B0: dcl_temps 2
   0  0x000000B8: div r0.xy, v3.xyxx, v3.wwww
   1  0x000000D4: min r0.xy, r0.xyxx, cb2[22].zwzz
   2  0x000000F4: sample_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t1.xyzw, s2
   3  0x00000120: add r0.x, -r0.x, v3.w
   4  0x00000140: div_sat r0.x, |r0.x|, cb3[7].w
   5  0x00000164: add r0.x, -r0.x, l(1.000000)
   6  0x00000184: log r0.x, r0.x
   7  0x00000198: mul r0.x, r0.x, cb3[8].x
   8  0x000001B8: exp r0.x, r0.x
   9  0x000001CC: add r0.x, -r0.x, l(1.000000)
  10  0x000001EC: max r0.x, r0.x, l(0.000000)
  11  0x00000208: sample_indexable(texture2darray)(float,float,float,float) r1.xyzw, v1.xyzx, t0.xyzw, s1
  12  0x00000234: mul r0.yz, r1.xxyx, cb3[2].xxyx
  13  0x00000254: add r0.y, r0.z, r0.y
  14  0x00000270: mad r0.y, cb3[2].z, r1.z, r0.y
  15  0x00000298: mad r0.y, cb3[2].w, r1.w, r0.y
  16  0x000002C0: mul r0.y, r0.y, v4.w
  17  0x000002DC: mul r0.x, r0.x, r0.y
  18  0x000002F8: mad r1.x, r0.x, cb3[8].y, cb3[1].x
  19  0x00000324: log r0.x, r0.x
  20  0x00000338: mul r0.x, r0.x, cb3[9].x
  21  0x00000358: exp o0.w, r0.x
  22  0x0000036C: add r0.x, v4.x, cb3[8].z
  23  0x0000038C: lt r0.x, r0.x, l(0.500000)
  24  0x000003A8: movc r1.z, r0.x, cb3[8].w, l(2.000000)
  25  0x000003D0: mov r1.y, l(0)
  26  0x000003E4: sample_l_indexable(texture2darray)(float,float,float,float) r0.xyz, r1.xyzx, t2.xyzw, s0, l(0.000000)
  27  0x00000418: mul r0.xyz, r0.xyzx, cb3[0].yzwy
  28  0x00000438: movc r0.w, cb3[0].x, cb2[24].w, l(1.000000)
  29  0x00000464: mul r0.xyz, r0.xyzx, r0.wwww
  30  0x00000480: mul r1.xyz, r0.xyzx, cb2[26].wwww
  31  0x000004A0: movc o0.xyz, cb3[0].xxxx, r1.xyzx, r0.xyzx
  32  0x000004C8: ret 
// Approximately 0 instruction slots used

*/