// ---- Created with 3Dmigoto v1.3.16 on Sat Jun 13 00:23:27 2026
Texture2D<float4> t4 : register(t4);

Texture2D<float4> t2 : register(t2);

SamplerState s4_s : register(s4);

SamplerState s0_s : register(s0);

cbuffer cb2 : register(b2)
{
  float4 cb2[4];
}

// 3Dmigoto declarations
#define cmp -
#define COMMON_LUT
#include "h1_common.hlsl"

void main(
  float4 v0 : SV_POSITION0,
  float2 v1 : TEXCOORD0,
  float2 w1 : TEXCOORD1,
  out float4 o0 : SV_TARGET0)
{
  float4 r0,r1,r2;
  uint4 bitmask, uiDest;
  float4 fDest;

  // Color
  LUT_Color(v1);

  // sRGB Encode
  LUT_Gamma();

  // No LUT

  // Saturation and Tint
  LUT_SaturationAndTint();

  // Overlay
  LUT_Overlay(w1, t2, s0_s);

  // Upgrade and Tonemap
  LUT_UpgradeAndTonemap();

  o0.xyz = li.r0;
  o0.w = 1;
  return;
}

/*

//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
// TEXCOORD                 1     zw        1     NONE   float     zw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      0x00000000: ps_5_0
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_constantbuffer CB2[4], immediateIndexed
      0x0000001C: dcl_sampler s0, mode_default
      0x00000028: dcl_sampler s4, mode_default
      0x00000034: dcl_resource_texture2d (float,float,float,float) t2
      0x00000044: dcl_resource_texture2d (float,float,float,float) t4
      0x00000054: dcl_input_ps linear v1.xy
      0x00000060: dcl_input_ps linear v1.zw
      0x0000006C: dcl_output o0.xyzw
      0x00000078: dcl_temps 3
   0  0x00000080: sample_indexable(texture2d)(float,float,float,float) r0.xyz, v1.xyxx, t4.xyzw, s4
   1  0x000000AC: mov_sat r0.xyz, r0.xyzx
   2  0x000000C0: log r1.xyz, r0.xyzx
   3  0x000000D4: mul r1.xyz, r1.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
   4  0x000000FC: exp r1.xyz, r1.xyzx
   5  0x00000110: mad r1.xyz, r1.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
   6  0x0000014C: ge r2.xyz, l(0.003131, 0.003131, 0.003131, 0.000000), r0.xyzx
   7  0x00000174: mul r0.xyz, r0.xyzx, l(12.920000, 12.920000, 12.920000, 0.000000)
   8  0x0000019C: movc r0.xyz, r2.xyzx, r0.xyzx, r1.xyzx
   9  0x000001C0: dp3 r0.w, r0.xyzx, l(0.299000, 0.587000, 0.114000, 0.000000)
  10  0x000001E8: mad r1.x, cb2[1].w, r0.w, cb2[0].w
  11  0x00000214: mov_sat r0.w, r0.w
  12  0x00000228: add r1.yzw, -r0.xxyz, r0.wwww
  13  0x00000248: mad r0.xyz, r1.xxxx, r1.yzwy, r0.xyzx
  14  0x0000026C: mad r1.xyz, cb2[2].xyzx, r0.wwww, cb2[1].xyzx
  15  0x00000298: mad r1.xyz, r1.xyzx, r0.wwww, cb2[0].xyzx
  16  0x000002C0: mad r0.xyz, r0.xyzx, r1.xyzx, cb2[3].xyzx
  17  0x000002E8: add r1.xyz, -r0.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  18  0x00000314: sample_indexable(texture2d)(float,float,float,float) r2.xyz, v1.zwzz, t2.xyzw, s0
  19  0x00000340: mad o0.xyz, r2.xyzx, r1.xyzx, r0.xyzx
  20  0x00000364: mov o0.w, l(1.000000)
  21  0x00000378: ret 
// Approximately 0 instruction slots used


*/