// ---- Created with 3Dmigoto v1.3.16 on Fri Jun 12 12:45:19 2026
Texture2D<float4> t4 : register(t4);

Texture3D<float4> t2 : register(t2);

SamplerState s4_s : register(s4);

SamplerState s0_s : register(s0);

cbuffer cb2 : register(b2)
{
  float4 cb2[4];
}

// 3Dmigoto declarations
#define cmp -
#define COMMON_LUT
#include "h1_common.hlsl"



void main(
  float4 v0 : SV_POSITION0,
  float2 v1 : TEXCOORD0,
  out float4 o0 : SV_TARGET0)
{
  float4 r0,r1,r2;
  uint4 bitmask, uiDest;
  float4 fDest;
  o0.w = 1;

  // Color
  LUT_Color(v1);

  // sRGB Encode
  LUT_Gamma();
  // o0.xyz = li.r0; return; //debug

  // LUT (sRGB -> sRGB)
  LUT_LUT(t2, s0_s);

  // Saturation and Tint
  LUT_SaturationAndTint();

  // Upgrade and Tonemap
  LUT_UpgradeAndTonemap();

  o0.xyz = li.r0;
  return;
}

/*

//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      0x00000000: ps_5_0
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_constantbuffer CB2[33], immediateIndexed
      0x0000001C: dcl_constantbuffer CB4[4], immediateIndexed
      0x0000002C: dcl_sampler s0, mode_default
      0x00000038: dcl_sampler s4, mode_default
      0x00000044: dcl_resource_texture2d (float,float,float,float) t2
      0x00000054: dcl_resource_texture2d (float,float,float,float) t4
      0x00000064: dcl_input_ps linear v1.xy
      0x00000070: dcl_output o0.xyzw
      0x0000007C: dcl_temps 5
   0  0x00000084: max r0.xy, v1.xyxx, cb2[32].xyxx
   1  0x000000A4: min r0.xy, r0.xyxx, cb2[32].zwzz
   2  0x000000C4: sample_indexable(texture2d)(float,float,float,float) r0.xyz, r0.xyxx, t2.xyzw, s0
   3  0x000000F0: mul r0.xyz, r0.xyzx, cb2[28].xxxx
   4  0x00000110: max r1.xy, v1.xyxx, cb2[31].xyxx
   5  0x00000130: min r1.xy, r1.xyxx, cb2[31].zwzz
   6  0x00000150: sample_indexable(texture2d)(float,float,float,float) r1.xyz, r1.xyxx, t4.xyzw, s4
   7  0x0000017C: mad r0.xyz, cb2[28].yyyy, r1.xyzx, r0.xyzx
   8  0x000001A4: ge r1.xyz, cb4[0].xxxx, r0.xyzx
   9  0x000001C4: movc r2.xyz, r1.xyzx, l(0,0,0,0), l(1.000000,1.000000,1.000000,0)
  10  0x00000200: and r1.xyz, r1.xyzx, l(0x3f800000, 0x3f800000, 0x3f800000, 0)
  11  0x00000228: mul r3.xyz, r2.xyzx, cb4[1].xxxx
  12  0x00000248: mad r3.xyz, r1.xyzx, cb4[2].xxxx, r3.xyzx
  13  0x00000270: mul r4.xyz, r2.xyzx, cb4[1].zzzz
  14  0x00000290: mad r4.xyz, r1.xyzx, cb4[2].zzzz, r4.xyzx
  15  0x000002B8: mad r3.xyz, r0.xyzx, r3.xyzx, r4.xyzx
  16  0x000002DC: mul r4.xyz, r2.xyzx, cb4[1].yyyy
  17  0x000002FC: mul r2.xyz, r2.xyzx, cb4[1].wwww
  18  0x0000031C: mad r2.xyz, r1.xyzx, cb4[2].wwww, r2.xyzx
  19  0x00000344: mad r1.xyz, r1.xyzx, cb4[2].yyyy, r4.xyzx
  20  0x0000036C: mad r0.xyz, r0.xyzx, r1.xyzx, r2.xyzx
  21  0x00000390: div_sat r0.xyz, r3.xyzx, r0.xyzx
  22  0x000003AC: log r0.xyz, r0.xyzx
  23  0x000003C0: mul r0.xyz, r0.xyzx, cb4[3].zzzz
  24  0x000003E0: exp o0.xyz, r0.xyzx
  25  0x000003F4: mov o0.w, l(1.000000)
  26  0x00000408: ret 
// Approximately 0 instruction slots used

*/