// ---- Created with 3Dmigoto v1.3.16 on Wed Jun 17 21:13:28 2026
Texture2D<float4> t2 : register(t2);

SamplerState s0_s : register(s0);

cbuffer cb2 : register(b2)
{
  float4 cb2[27];
}

// 3Dmigoto declarations
#define cmp -
#include "./Includes/Common.hlsl"


void main(
  float4 v0 : SV_POSITION0,
  float4 v1 : TEXCOORD0,
  out float4 o0 : SV_TARGET0)
{
  float4 r0,r1;
  uint4 bitmask, uiDest;
  float4 fDest;
  o0.zw = float2(0,0);

  r0.z = t2.SampleLevel(s0_s, v1.xy, 0).x; //depth

  // motion vectors for viewmodel is just the world behind it but 1000x, unusable...
  if (r0.z >= 0.9) {
    o0.xy = float2(0,0);
    return;
  }

  //proj stuff
  r0.xy = v1.xy;
  r0.w = 1;
  r1.x = dot(r0.xyzw, cb2[6].xyzw);
  r1.y = dot(r0.xyzw, cb2[7].xyzw);
  r0.x = dot(r0.xyzw, cb2[8].xyzw);
  r0.xy = r1.xy / r0.xx;
  r0.xy = v1.xy + -r0.xy; //linear uv space here
  r0.xy = cb2[26].xy * r0.xy; //scale by internal resolution

  //encoding
  r0.zw = float2(0.25,0.25) * abs(r0.xy);
  r0.zw = min(float2(1,1), r0.zw);
  r1.xy = float2(-4,-4) + abs(r0.xy);
  r0.xy = cmp(r0.xy >= float2(0,0));
  r1.xy = saturate(float2(0.027777778,0.027777778) * r1.xy);
  r1.xy = sqrt(r1.xy);
  r0.zw = -r1.xy + r0.zw;
  r0.zw = r0.zw * float2(0.5,0.5) + r1.xy;
  r0.xy = r0.xy ? r0.zw : -r0.zw;
  // r0.xy = clamp(r0.xy, -1, 1); //snorm

  //out
  o0.xy = r0.xy;
  return;
}

/*
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xyzw        1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      0x00000000: ps_5_0
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_constantbuffer CB2[27], immediateIndexed
      0x0000001C: dcl_sampler s0, mode_default
      0x00000028: dcl_resource_texture2d (float,float,float,float) t2
      0x00000038: dcl_input_ps linear v1.xy
      0x00000044: dcl_output o0.xyzw
      0x00000050: dcl_temps 2
   0  0x00000058: sample_l_indexable(texture2d)(float,float,float,float) r0.z, v1.xyxx, t2.yzxw, s0, l(0.000000)
   1  0x0000008C: mov r0.xy, v1.xyxx
   2  0x000000A0: mov r0.w, l(1.000000)
   3  0x000000B4: dp4 r1.x, r0.xyzw, cb2[6].xyzw
   4  0x000000D4: dp4 r1.y, r0.xyzw, cb2[7].xyzw
   5  0x000000F4: dp4 r0.x, r0.xyzw, cb2[8].xyzw
   6  0x00000114: div r0.xy, r1.xyxx, r0.xxxx
   7  0x00000130: add r0.xy, -r0.xyxx, v1.xyxx
   8  0x00000150: mul r0.xy, r0.xyxx, cb2[26].xyxx
   9  0x00000170: mul r0.zw, |r0.xxxy|, l(0.000000, 0.000000, 0.250000, 0.250000)
  10  0x0000019C: min r0.zw, r0.zzzw, l(0.000000, 0.000000, 1.000000, 1.000000)
  11  0x000001C4: add r1.xy, |r0.xyxx|, l(-4.000000, -4.000000, 0.000000, 0.000000)
  12  0x000001F0: ge r0.xy, r0.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
  13  0x00000218: mul_sat r1.xy, r1.xyxx, l(0.027778, 0.027778, 0.000000, 0.000000)
  14  0x00000240: sqrt r1.xy, r1.xyxx
  15  0x00000254: add r0.zw, r0.zzzw, -r1.xxxy
  16  0x00000274: mad r0.zw, r0.zzzw, l(0.000000, 0.000000, 0.500000, 0.500000), r1.xxxy
  17  0x000002A4: movc o0.xy, r0.xyxx, r0.zwzz, -r0.zwzz
  18  0x000002CC: mov o0.zw, l(0,0,0,0)
  19  0x000002EC: ret 
// Approximately 0 instruction slots used
*/