// ---- Created with 3Dmigoto v1.3.16 on Fri Jun 12 12:45:19 2026
Texture2D<float4> t4 : register(t4); //linear color

Texture2D<float4> t2 : register(t2); //bloom

SamplerState s4_s : register(s4);

SamplerState s0_s : register(s0);

cbuffer cb4 : register(b4)
{
  float4 cb4[4];
}

cbuffer cb2 : register(b2)
{
  float4 cb2[33];
}

// 3Dmigoto declarations
#define cmp -
#include "common.hlsl"

void main(
  float4 v0 : SV_POSITION0,
  float2 v1 : TEXCOORD0,
  out float4 o0 : SV_TARGET0)
{
  float4 r0,r1,r2,r3,r4;
  uint4 bitmask, uiDest;
  float4 fDest;
  o0 = 0;

  // Bloom
  r0.xy = clamp(v1.xy, cb2[32].xy, cb2[32].zw);
  r0.xyz = t2.Sample(s0_s, r0.xy).xyz;
  r0.xyz = cb2[28].xxx * r0.xyz * GS.Bloom; //bloom strength

  // Color
  r1.xy = clamp(v1.xy, cb2[31].xy, cb2[31].zw);
  r1.xyz = t4.Sample(s4_s, r1.xy).xyz;

  // Exposure & Bloom
  r1.xyz = cb2[28].y * r1.xyz; //post process volume exposure * color
  r0.xyz = r1.xyz + r0.xyz; //+ bloom HDR

  /////////////////////////////////////////////////////////////////////////////////////

//   // Setup
//   float3 colorU, colorT;
//   float3 x = r0.xyz;
// 
//   // SDR
//   float3 lower = MobiusRolloff(x, cb4[2]); //when thres = \inf
//   float3 upper = MobiusRolloff(x, cb4[1]); //when thres = 0
//   colorT = x < cb4[0].x ? lower : upper; //piecewise point/threshold
//   colorT = ClampByMaxChannel(colorT, 1); //clean
//   colorT = max(colorT, 0); //clean
//   // colorT = saturate(colorT); //clean
//   float colorTMax = max(colorT.x, max(colorT.y, colorT.z));
// 
//   // HDR
//   float4 c = cb4[0].x > 0 ? cb4[2] : cb4[1]; //use lower unless threshold is 0
//   float slope_at_piecewise = MobiusRolloffDerivative(cb4[0].x, c);
//   float output_at_piecewise = MobiusRolloff(cb4[0].x, c);
//   float output_at_piecewise_safe = max(output_at_piecewise, 0.0001);
//   float3 lower_hdr = colorT; //lower from SDR
//   float3 upper_hdr = slope_at_piecewise * (x - cb4[0].x) + output_at_piecewise; //mx + b
//   colorU = x < cb4[0].x ? lower_hdr : upper_hdr;
//   colorU = max(colorU, 0); //clean
// 
//   // HDR out
//   o0.w = GetLuminance(colorU, CS_BT709);
// 
//   // HDR Blowout
//   {
//     // Forced blowout
//     colorU = Rolloff_HDRRolloff(colorU, output_at_piecewise_safe); 
// 
//     // 100% steal
//     float colorTy = GetLuminance(colorT, CS_BT709);
//     float colorUy = GetLuminance(colorU, CS_BT709);
//     colorU *= safeDivision(colorTy, colorUy, 1);
//     colorT = colorU;
//     
//     // // UCS Steal //TODO: remove, this causes too much flat yellow in explosions.
//     // colorU = UCS_ToUCS(colorU);
//     // colorT = UCS_ToUCS(colorT);
//     // colorT = RestoreHueAndChrominanceUcs(colorT, colorU, 0.45, 0.8, 0); 
//     // colorT = UCS_FromUCS(colorT); //and colorU is unused after this
//   }
// 
//   // SDR Clean
//   colorT = max(colorT, 0);
//   colorT = ClampByMaxChannel(colorT, min(1, colorTMax)); //cram, ensure max chrominance
//   r0.xyz = colorT; //update r0 with the cleaned SDR color

  RolloffResult r = Rolloff_Complete(r0.xyz, cb4[0].x, cb4[1], cb4[2]);
  r0.xyz = r.color;
  o0.w = r.y;

  // Gamma (Not user, usually 1)
  r0.xyz = pow(r0.xyz, cb4[3].z);

  // SDR out
  o0.xyz = r0.xyz;
  return;
}

/*

//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      0x00000000: ps_5_0
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_constantbuffer CB2[4], immediateIndexed
      0x0000001C: dcl_sampler s0, mode_default
      0x00000028: dcl_sampler s4, mode_default
      0x00000034: dcl_resource_texture3d (float,float,float,float) t2
      0x00000044: dcl_resource_texture2d (float,float,float,float) t4
      0x00000054: dcl_input_ps linear v1.xy
      0x00000060: dcl_output o0.xyzw
      0x0000006C: dcl_temps 3
   0  0x00000074: sample_indexable(texture2d)(float,float,float,float) r0.xyz, v1.xyxx, t4.xyzw, s4
   1  0x000000A0: mov_sat r0.xyz, r0.xyzx
   2  0x000000B4: log r1.xyz, r0.xyzx
   3  0x000000C8: mul r1.xyz, r1.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
   4  0x000000F0: exp r1.xyz, r1.xyzx
   5  0x00000104: mad r1.xyz, r1.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
   6  0x00000140: ge r2.xyz, l(0.003131, 0.003131, 0.003131, 0.000000), r0.xyzx
   7  0x00000168: mul r0.xyz, r0.xyzx, l(12.920000, 12.920000, 12.920000, 0.000000)
   8  0x00000190: movc r0.xyz, r2.xyzx, r0.xyzx, r1.xyzx
   9  0x000001B4: mad r0.xyz, r0.xyzx, l(0.968750, 0.968750, 0.968750, 0.000000), l(0.015625, 0.015625, 0.015625, 0.000000)
  10  0x000001F0: sample_indexable(texture3d)(float,float,float,float) r0.xyz, r0.xyzx, t2.xyzw, s0
  11  0x0000021C: dp3 r0.w, r0.xyzx, l(0.299000, 0.587000, 0.114000, 0.000000)
  12  0x00000244: mad r1.x, cb2[1].w, r0.w, cb2[0].w
  13  0x00000270: mov_sat r0.w, r0.w
  14  0x00000284: add r1.yzw, -r0.xxyz, r0.wwww
  15  0x000002A4: mad r0.xyz, r1.xxxx, r1.yzwy, r0.xyzx
  16  0x000002C8: mad r1.xyz, cb2[2].xyzx, r0.wwww, cb2[1].xyzx
  17  0x000002F4: mad r1.xyz, r1.xyzx, r0.wwww, cb2[0].xyzx
  18  0x0000031C: mad o0.xyz, r0.xyzx, r1.xyzx, cb2[3].xyzx
  19  0x00000344: mov o0.w, l(1.000000)
  20  0x00000358: ret 
// Approximately 0 instruction slots used

*/