// ---- Created with 3Dmigoto v1.3.16 on Mon Jun 15 16:22:29 2026
Texture2D<float4> t4 : register(t4);

Texture2D<float4> t2 : register(t2);

SamplerState s4_s : register(s4);

SamplerState s0_s : register(s0);

cbuffer cb4 : register(b4)
{
  float4 cb4[68];
}

cbuffer cb2 : register(b2)
{
  float4 cb2[38];
}


// 3Dmigoto declarations
#define cmp -
#include "h2_common.hlsl"

void main(
  float4 v0 : SV_POSITION0,
  float2 v1 : TEXCOORD0,
  out float4 o0 : SV_TARGET0)
{
  float4 r0,r1,r2,r3,r4;
  uint4 bitmask, uiDest;
  float4 fDest;
  o0.w = 1;

  // Bloom & Color
  r0.xy = max(cb2[37].xy, v1.xy);
  r0.xy = min(cb2[37].zw, r0.xy);
  r0.xyz = t2.Sample(s0_s, r0.xy).xyz;
  r0.xyz = cb2[33].xxx * GS.Bloom * r0.xyz ;

  r1.xyz = t4.Sample(s4_s, v1.xy).xyz;
  r0.xyz = cb2[33].yyy * r1.xyz + r0.xyz;

  TM_Color(r0.xyz);

  // Piecewise Mobius
  TM_Rolloff();

  // Luminance Per-Channel
  TM_LumaThingy();

  // sRGB Encode
  TM_Gamma();

  // Saturation and Tint
  TM_SaturationAndTint();

  // Upgrade
  TM_Upgrade();
  
  // Dither (ewww)
  // r1.xy = cb2[21].yz + v1.xy;
  // r0.w = dot(r1.xy, float2(353632.0, 4234.0));
  // uint r0w = (uint)r0.w;
  // uint r1x = (uint)((int)r0w ^ 61);
  // r0w = r0w >> 16u;
  // r0w = (uint)((int)r0w ^ (int)r1x);
  // r0w = (uint)((int)r0w * 7);
  // r1x = r0w >> 4u;
  // r0w = (uint)((int)r0w ^ (int)r1x);
  // int3 r1xyz = (int)r0w * int3(356, 2543, 0x424df4);
  // r1xyz = r1xyz & int3(0x3fffc, 0x3ffff, 0x7fffc);
  // r0.xyz = asfloat(asint(r0.xyz) + r1xyz);

  o0.xyz = tmi.r0;
  return;
}

/*

//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      0x00000000: ps_5_0
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_constantbuffer CB2[38], immediateIndexed
      0x0000001C: dcl_constantbuffer CB4[68], immediateIndexed
      0x0000002C: dcl_sampler s0, mode_default
      0x00000038: dcl_sampler s4, mode_default
      0x00000044: dcl_resource_texture2d (float,float,float,float) t2
      0x00000054: dcl_resource_texture2d (float,float,float,float) t4
      0x00000064: dcl_input_ps linear v1.xy
      0x00000070: dcl_output o0.xyzw
      0x0000007C: dcl_temps 5
   0  0x00000084: max r0.xy, v1.xyxx, cb2[37].xyxx
   1  0x000000A4: min r0.xy, r0.xyxx, cb2[37].zwzz
   2  0x000000C4: sample_indexable(texture2d)(float,float,float,float) r0.xyz, r0.xyxx, t2.xyzw, s0
   3  0x000000F0: mul r0.xyz, r0.xyzx, cb2[33].xxxx
   4  0x00000110: sample_indexable(texture2d)(float,float,float,float) r1.xyz, v1.xyxx, t4.xyzw, s4
   5  0x0000013C: mad r0.xyz, cb2[33].yyyy, r1.xyzx, r0.xyzx
   6  0x00000164: ge r1.xyz, cb4[0].xxxx, r0.xyzx
   7  0x00000184: movc r2.xyz, r1.xyzx, l(0,0,0,0), l(1.000000,1.000000,1.000000,0)
   8  0x000001C0: and r1.xyz, r1.xyzx, l(0x3f800000, 0x3f800000, 0x3f800000, 0)
   9  0x000001E8: mul r3.xyz, r2.xyzx, cb4[1].xxxx
  10  0x00000208: mad r3.xyz, r1.xyzx, cb4[2].xxxx, r3.xyzx
  11  0x00000230: mul r4.xyz, r2.xyzx, cb4[1].zzzz
  12  0x00000250: mad r4.xyz, r1.xyzx, cb4[2].zzzz, r4.xyzx
  13  0x00000278: mad r3.xyz, r0.xyzx, r3.xyzx, r4.xyzx
  14  0x0000029C: mul r4.xyz, r2.xyzx, cb4[1].yyyy
  15  0x000002BC: mul r2.xyz, r2.xyzx, cb4[1].wwww
  16  0x000002DC: mad r2.xyz, r1.xyzx, cb4[2].wwww, r2.xyzx
  17  0x00000304: mad r1.xyz, r1.xyzx, cb4[2].yyyy, r4.xyzx
  18  0x0000032C: mad r0.xyz, r0.xyzx, r1.xyzx, r2.xyzx
  19  0x00000350: div_sat r0.xyz, r3.xyzx, r0.xyzx
  20  0x0000036C: log r0.xyz, r0.xyzx
  21  0x00000380: mul r0.xyz, r0.xyzx, cb4[3].zzzz
  22  0x000003A0: exp r0.xyz, r0.xyzx
  23  0x000003B4: dp3_sat r1.x, r0.xyzx, cb4[65].xyzx
  24  0x000003D4: dp3_sat r1.y, r0.xyzx, cb4[66].xyzx
  25  0x000003F4: dp3_sat r1.z, r0.xyzx, cb4[67].xyzx
  26  0x00000414: log r0.xyz, r1.xyzx
  27  0x00000428: mul r0.xyz, r0.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
  28  0x00000450: exp r0.xyz, r0.xyzx
  29  0x00000464: mad r0.xyz, r0.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
  30  0x000004A0: ge r2.xyz, l(0.003131, 0.003131, 0.003131, 0.000000), r1.xyzx
  31  0x000004C8: mul r1.xyz, r1.xyzx, l(12.920000, 12.920000, 12.920000, 0.000000)
  32  0x000004F0: movc r0.xyz, r2.xyzx, r1.xyzx, r0.xyzx
  33  0x00000514: dp3_sat r0.w, r0.xyzx, l(0.299000, 0.587000, 0.114000, 0.000000)
  34  0x0000053C: add r1.xyz, -r0.xyzx, r0.wwww
  35  0x0000055C: mad r1.w, cb2[1].w, r0.w, cb2[0].w
  36  0x00000588: mad r0.xyz, r1.wwww, r1.xyzx, r0.xyzx
  37  0x000005AC: mad r1.xyz, cb2[2].xyzx, r0.wwww, cb2[1].xyzx
  38  0x000005D8: mad r1.xyz, r1.xyzx, r0.wwww, cb2[0].xyzx
  39  0x00000600: mad r0.xyz, r0.xyzx, r1.xyzx, cb2[3].xyzx
  40  0x00000628: add r1.xy, v1.xyxx, cb2[21].yzyy
  41  0x00000648: dp2 r0.w, r1.xyxx, l(353632.000000, 4234.000000, 0.000000, 0.000000)
  42  0x00000670: ftou r0.w, r0.w
  43  0x00000684: xor r1.x, r0.w, l(61)
  44  0x000006A0: ushr r0.w, r0.w, l(16)
  45  0x000006BC: xor r0.w, r0.w, r1.x
  46  0x000006D8: imul null, r0.w, r0.w, l(7)
  47  0x000006F8: ushr r1.x, r0.w, l(4)
  48  0x00000714: xor r0.w, r0.w, r1.x
  49  0x00000730: imul null, r1.xyz, r0.wwww, l(356, 2543, 0x00424df4, 0)
  50  0x0000075C: and r1.xyz, r1.xyzx, l(0x0003fffc, 0x0003ffff, 0x0007fffc, 0)
  51  0x00000784: iadd o0.xyz, r0.xyzx, r1.xyzx
  52  0x000007A0: mov o0.w, l(1.000000)
  53  0x000007B4: ret 
// Approximately 0 instruction slots used


*/